export interface AnnualPlanItem {
  ay: string;
  hafta: string;
  haftaNo: number;
  saat: string;
  unite: string;
  konu: string;
  ogrenme_ciktisi: string;
  outcomeCode: string;
  surec_bilesenleri: string;
  ogrenme_kanitlari: string;
  sosyal_ve_duygusal_beceriler: string;
  degerler: string;
  okuryazarlik_becerileri: string;
  degerlendirme: string;
}

export const ANNUAL_PLAN_DATA: AnnualPlanItem[] = [
  {
    ay: "EYLÜL",
    hafta: "1. HAFTA (14-20 EYLÜL)",
    haftaNo: 1,
    saat: "5 SAAT",
    unite: "GEOMETRİK ŞEKİLLER",
    konu: "Temel Geometrik Çizimler ve İnşalar",
    ogrenme_ciktisi: "MAT.5.3.1. Temel geometrik çizimler için matematiksel araç ve teknolojiden yararlanabilme",
    outcomeCode: "MAT.5.3.1",
    surec_bilesenleri: "a) Nokta, doğru, doğru parçası, ışın, açı, çember ve dikme çiziminde gerekli araç ve teknolojileri tanır. b) Nokta, doğru, doğru parçası, ışın, açı, çember ve dikmeyi oluşturmak için uygun olan araç ve teknolojileri belirler. c) Nokta, doğru, doğru parçası, ışın, açı, çember ve dikmeyi oluşturmak için uygun araç ve teknolojileri kullanır.",
    ogrenme_kanitlari: "Gözlem formu, Çalışma kâğıdı, Kontrol listesi, Performans görevi, Öz değerlendirme ve Akran değerlendirme formları, Öğrenme günlüğü, Zihin haritası, İzleme testi",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık/Kendini Tanıma, SDB1.2. Öz Düzenleme/Kendini Düzenleme, SDB1.3. Öz Yansıtma/Kendine Uyarlama, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D7. Estetik, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: "2026-2027 Eğitim-Öğretim yılı başlangıcı"
  },
  {
    ay: "EYLÜL",
    hafta: "2. HAFTA (21-27 EYLÜL)",
    haftaNo: 2,
    saat: "5 SAAT",
    unite: "GEOMETRİK ŞEKİLLER",
    konu: "Temel Geometrik Çizimler ve İnşalar",
    ogrenme_ciktisi: "MAT.5.3.2. Temel geometrik çizimlere dayalı deneyimlerini yansıtabilme",
    outcomeCode: "MAT.5.3.2",
    surec_bilesenleri: "a) Temel geometrik çizimlere dayalı deneyimlerini gözden geçirir. b) Temel geometrik çizimlerin özelliklerine yönelik çıkarım yapar. c) Çıkarımını farklı örnekler üzerinden değerlendirir.",
    ogrenme_kanitlari: "Gözlem formu, Çalışma kâğıdı, Kontrol listesi, Performans görevi, Öz değerlendirme ve Akran değerlendirme formları, Öğrenme günlüğü, Zihin haritası, İzleme testi",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık/Kendini Tanıma, SDB1.2. Öz Düzenleme/Kendini Düzenleme, SDB1.3. Öz Yansıtma/Kendine Uyarlama, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D7. Estetik, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "EYLÜL-EKİM",
    hafta: "3. HAFTA (28 EYLÜL - 04 EKİM)",
    haftaNo: 3,
    saat: "5 SAAT",
    unite: "GEOMETRİK ŞEKİLLER",
    konu: "Açı Ölçme",
    ogrenme_ciktisi: "MAT.5.3.3. Açıları ölçmek için matematiksel araç ve teknolojiden yararlanabilme",
    outcomeCode: "MAT.5.3.3",
    surec_bilesenleri: "a) Açı ölçmek için gerekli araç ve teknolojiyi tanır. b) Açı ölçmek için uygun araç ve teknolojiyi belirler. c) Açı ölçmek için uygun araç ve teknolojiyi kullanır.",
    ogrenme_kanitlari: "Gözlem formu, Çalışma kâğıdı, Kontrol listesi, Performans görevi, Öz değerlendirme ve Akran değerlendirme formları, Öğrenme günlüğü, Zihin haritası, İzleme testi",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık/Kendini Tanıma, SDB1.2. Öz Düzenleme/Kendini Düzenleme, SDB1.3. Öz Yansıtma/Kendine Uyarlama, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D7. Estetik, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "EKİM",
    hafta: "4. HAFTA (05-11 EKİM)",
    haftaNo: 4,
    saat: "5 SAAT",
    unite: "GEOMETRİK ŞEKİLLER",
    konu: "Açı Ölçme",
    ogrenme_ciktisi: "MAT.5.3.4. Düzlemde iki veya üç doğrunun birbirine göre durumuna bağlı olarak oluşabilecek açılara dair çıkarım yapabilme",
    outcomeCode: "MAT.5.3.4",
    surec_bilesenleri: "a) Düzlemde iki veya üç doğrunun birbirine göre durumuna bağlı olarak oluşabilecek açılara dair varsayımlarda bulunur. b) Düzlemde iki veya üç doğrunun birbirine göre durumuna bağlı olarak oluşan açıları belirleyerek listeler. c) Belirlediği açıları varsayımlarıyla karşılaştırır. ç) Düzlemde iki veya üç doğrunun birbirine göre durumuna bağlı olarak oluşan açılara dair önerme sunar. d) Sunduğu önermelerin, doğruların oluşturduğu açıların incelenmesine yönelik katkısına dair gerekçe sunar.",
    ogrenme_kanitlari: "Gözlem formu, Çalışma kâğıdı, Kontrol listesi, Performans görevi, Öz değerlendirme ve Akran değerlendirme formları, Öğrenme günlüğü, Zihin haritası, İzleme testi",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık/Kendini Tanıma, SDB1.2. Öz Düzenleme/Kendini Düzenleme, SDB1.3. Öz Yansıtma/Kendine Uyarlama, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D7. Estetik, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "EKİM",
    hafta: "5. HAFTA (12-18 EKİM)",
    haftaNo: 5,
    saat: "5 SAAT",
    unite: "GEOMETRİK ŞEKİLLER",
    konu: "Çokgenler ve Çember",
    ogrenme_ciktisi: "MAT.5.3.5. Çokgenleri düzlemde ardışık olarak kesişen doğruların oluşturduğu kapalı şekiller olarak yorumlayabilme",
    outcomeCode: "MAT.5.3.5",
    surec_bilesenleri: "a) Düzlemde en az üç doğrunun -son doğru ilk doğruyla kesişecek biçimde- ardışık kesişerek oluşturdukları durumları inceler. b) Düzlemde en az üç doğrunun -son doğru ilk doğruyla kesişecek biçimde- ardışık kesişimleri ile çeşitli çokgenler oluşturur. c) Çokgenlerin düzlemde en az üç doğrunun -son doğru ilk doğruyla kesişecek biçimde- ardışık kesişimleri ile meydana geldiğini ifade eder.",
    ogrenme_kanitlari: "Gözlem formu, Çalışma kâğıdı, Kontrol listesi, Performans görevi, Öz değerlendirme ve Akran değerlendirme formları, Öğrenme günlüğü, Zihin haritası, İzleme testi",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık/Kendini Tanıma, SDB1.2. Öz Düzenleme/Kendini Düzenleme, SDB1.3. Öz Yansıtma/Kendine Uyarlama, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D7. Estetik, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "EKİM",
    hafta: "6. HAFTA (19-25 EKİM)",
    haftaNo: 6,
    saat: "5 SAAT",
    unite: "GEOMETRİK ŞEKİLLER",
    konu: "Çokgenler ve Çember",
    ogrenme_ciktisi: "MAT.5.3.6. Çokgenlerin özellikleri ile ilgili edindiği deneyimleri yansıtabilme",
    outcomeCode: "MAT.5.3.6",
    surec_bilesenleri: "a) Çokgenlerin özellikleri ile ilgili edindiği deneyimleri gözden geçirir. b) Çokgenlerin kenar ve açı özelliklerine dair çıkarım yapar. c) Çıkarımını farklı örnekler üzerinden değerlendirir.",
    ogrenme_kanitlari: "Gözlem formu, Çalışma kâğıdı, Kontrol listesi, Performans görevi, Öz değerlendirme ve Akran değerlendirme formları, Öğrenme günlüğü, Zihin haritası, İzleme testi",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık/Kendini Tanıma, SDB1.2. Öz Düzenleme/Kendini Düzenleme, SDB1.3. Öz Yansıtma/Kendine Uyarlama, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D7. Estetik, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "EKİM-KASIM",
    hafta: "7. HAFTA (26 EKİM - 01 KASIM)",
    haftaNo: 7,
    saat: "5 SAAT",
    unite: "GEOMETRİK ŞEKİLLER",
    konu: "Çokgenler ve Çember",
    ogrenme_ciktisi: "MAT.5.3.7. Matematiksel araç ve teknoloji yardımıyla düzlemde iki noktada kesişen çember çiftinin merkezleri ve kesişim noktalarından biri ile inşa edilen üçgenlerin kenar özelliklerine yönelik muhakeme yapabilme",
    outcomeCode: "MAT.5.3.7",
    surec_bilesenleri: "a) İki noktada kesişen çember çiftinin merkezleri ve kesişim noktalarından biri ile inşa edilebilecek üçgenlerin kenar özelliklerine yönelik varsayımlarda bulunur. b) Örnek çizimler üzerinden, kesişen iki çemberin merkezleri ve kesişim noktalarından biri ile inşa edilen çeşitkenar, ikizkenar ve eşkenar üçgenleri belirler. c) Belirlediği üçgenlerin özelliklerini varsayımları ile karşılaştırır. ç) Varsayımlarını, inşa ettiği üçgenler ile karşılaştırarak doğrulayabileceği önermeler şeklinde ifade eder. d) Sunduğu önermelerin katkısını değerlendirir. e) Çemberin özelliklerini kullanarak önermelerini doğrulamaya yönelik matematiksel gerekçeler sunar. f) Çemberin özelliklerinin benzer inşa süreçlerindeki rolünü değerlendirir.",
    ogrenme_kanitlari: "Gözlem formu, Çalışma kâğıdı, Kontrol listesi, Performans görevi, Öz değerlendirme ve Akran değerlendirme formları, Öğrenme günlüğü, Zihin haritası, İzleme testi",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık/Kendini Tanıma, SDB1.2. Öz Düzenleme/Kendini Düzenleme, SDB1.3. Öz Yansıtma/Kendine Uyarlama, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D7. Estetik, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: "Cumhuriyet Bayramı"
  },
  {
    ay: "KASIM",
    hafta: "8. HAFTA (02-08 KASIM)",
    haftaNo: 8,
    saat: "5 SAAT",
    unite: "GEOMETRİK ŞEKİLLER",
    konu: "Çokgenler ve Çember",
    ogrenme_ciktisi: "MAT.5.3.7. Matematiksel araç ve teknoloji yardımıyla düzlemde照射 iki noktada kesişen çember çiftinin merkezleri ve kesişim noktalarından biri ile inşa edilen üçgenlerin kenar özelliklerine yönelik muhakeme yapabilme",
    outcomeCode: "MAT.5.3.7",
    surec_bilesenleri: "a) İki noktada kesişen çember çiftinin merkezleri ve kesişim noktalarından biri ile inşa edilebilecek üçgenlerin kenar özelliklerine yönelik varsayımlarda bulunur. b) Örnek çizimler üzerinden, kesişen iki çemberin merkezleri ve kesişim noktalarından biri ile inşa edilen çeşitkenar, ikizkenar ve eşkenar üçgenleri belirler. c) Belirlediği üçgenlerin özelliklerini varsayımları ile karşılaştırır. ç) Varsayımlarını, inşa ettiği üçgenler ile karşılaştırarak doğrulayabileceği önermeler şeklinde ifade eder. d) Sunduğu önermelerin katkısını değerlendirir. e) Çemberin özelliklerini kullanarak önermelerini doğrulamaya yönelik matematiksel gerekçeler sunar. f) Çemberin özelliklerinin benzer inşa süreçlerindeki rolünü değerlendirir.",
    ogrenme_kanitlari: "Gözlem formu, Çalışma kâğıdı, Kontrol listesi, Performans görevi, Öz değerlendirme ve Akran değerlendirme formları, Öğrenme günlüğü, Zihin haritası, İzleme testi",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık/Kendini Tanıma, SDB1.2. Öz Düzenleme/Kendini Düzenleme, SDB1.3. Öz Yansıtma/Kendine Uyarlama, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D7. Estetik, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: "Kızılay Haftası"
  },
  {
    ay: "KASIM",
    hafta: "9. HAFTA (09-15 KASIM)",
    haftaNo: 9,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (1)",
    konu: "Çok Basamaklı Sayıları Okuma ve Yazma",
    ogrenme_ciktisi: "MAT.5.1.1. Altı basamaklı sayıları okuma ve yazmayı çok basamaklı sayılara genelleyebilme",
    outcomeCode: "MAT.5.1.1",
    surec_bilesenleri: "a) Günlük hayattaki farklı bağlamlardan yola çıkarak altıdan çok basamaklı sayılar hakkında bilgi toplar. b) Sayıların bölükleri ile okunuşları arasındaki ortak özellikleri belirler. c) Sayıların bölükleri ile okunuşları arasındaki örüntüler üzerinden basamak sayısı altıdan çok olan sayıların okunuş ve yazılışları hakkında önermelerde bulunur.",
    ogrenme_kanitlari: "Açık uçlu sorulardan oluşan çalışma kağıdı, İzleme testi, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.2. İş Birliği, SDB3.2. Esneklik",
    degerler: "D3. Çalışkanlık, D7. Estetik, D16. Sorumluluk, D17. Tasarruf",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: "Atatürk Haftası"
  },
  {
    ay: "KASIM",
    hafta: "10. HAFTA (23-29 KASIM)",
    haftaNo: 10,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (1)",
    konu: "Çözümleme",
    ogrenme_ciktisi: "MAT.5.1.1. Altı basamaklı sayıları okuma ve yazmayı çok basamaklı sayılara genelleyebilme",
    outcomeCode: "MAT.5.1.1",
    surec_bilesenleri: "a) Günlük hayattaki farklı bağlamlardan yola çıkarak altıdan çok basamaklı sayılar hakkında bilgi toplar. b) Sayıların bölükleri ile okunuşları arasındaki ortak özellikleri belirler. c) Sayıların bölükleri ile okunuşları arasındaki örüntüler üzerinden basamak sayısı altıdan çok olan sayıların okunuş ve yazılışları hakkında önermelerde bulunur.",
    ogrenme_kanitlari: "Açık uçlu sorulardan oluşan çalışma kağıdı, İzleme testi, Performans görevi, Öz değerlendirme ve akran değerlendirme formları",
    sosyal_ve_duygusal_beceriler: "SDB2.2. İş Birliği, SDB3.2. Esneklik",
    degerler: "D3. Çalışkanlık, D7. Estetik, D16. Sorumluluk, D17. Tasarruf",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: "Öğretmenler Günü"
  },
  {
    ay: "KASIM-ARALIK",
    hafta: "11. HAFTA (30 KASIM - 06 ARALIK)",
    haftaNo: 11,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (1)",
    konu: "Doğal Sayılarla Dört İşlem İçeren Problem Çözme",
    ogrenme_ciktisi: "MAT.5.1.2. Doğal sayılar ve işlemler içeren gerçek yaşam problemlerini çözebilme",
    outcomeCode: "MAT.5.1.2",
    surec_bilesenleri: "a) Problemin içerdiği sayı ve işlem bileşenlerini belirler. b) Problemde verilenler ile istenenlerin gerektirdiği işlemler arasındaki ilişkiyi belirler. c) Problem bağlamıyla ilişkili verilenleri uygun matematiksel temsillere dönüştürür. ç) Problemi matematiksel temsiller kullanarak kendi ifadeleri ile açıklar. d) Problemin sonucuna ilişkin tahminde bulunur ve işlemleri gerçekleştirmek için stratejiler geliştirir. e) Belirlenen strateji veya stratejileri çözüm için uygular. f) Çözüm yollarını kontrol eder ve çözüme ulaştırmayan stratejiyi değiştirir. g) Problemin çözümü için kullandığı veya geliştirdiği stratejileri gözden geçirerek kısa yolları değerlendirir. ğ) Kullandığı strateji veya stratejileri farklı problemlerin çözümlerine geneller. h) Genellemenin geçerliliğini matematiksel örneklerle değerlendirir.",
    ogrenme_kanitlari: "Açık uçlu sorulardan oluşan çalışma kağıdı, İzleme testi, Performans görevi, Öz değerlendirme ve akran değerlendirme formları",
    sosyal_ve_duygusal_beceriler: "SDB2.2. İş Birliği, SDB3.2. Esneklik",
    degerler: "D3. Çalışkanlık, D7. Estetik, D16. Sorumluluk, D17. Tasarruf",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "ARALIK",
    hafta: "12. HAFTA (07-13 ARALIK)",
    haftaNo: 12,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (1)",
    konu: "Doğal Sayılarla Dört İşlem İçeren Problem Çözme",
    ogrenme_ciktisi: "MAT.5.1.2. Doğal sayılar ve işlemler içeren gerçek yaşam problemlerini çözebilme",
    outcomeCode: "MAT.5.1.2",
    surec_bilesenleri: "a) Problemin içerdiği sayı ve işlem bileşenlerini belirler. b) Problemde verilenler ile istenenlerin gerektirdiği işlemler arasındaki ilişkiyi belirler. c) Problem bağlamıyla ilişkili verilenleri uygun matematiksel temsillere dönüştürür. ç) Problemi matematiksel temsiller kullanarak kendi ifadeleri ile açıklar. d) Problemin sonucuna ilişkin tahminde bulunur ve işlemleri gerçekleştirmek için stratejiler geliştirir. e) Belirlenen strateji veya stratejileri çözüm için uygular. f) Çözüm yollarını kontrol eder ve çözüme ulaştırmayan stratejiyi değiştirir. g) Problemin çözümü için kullandığı veya geliştirdiği stratejileri gözden geçirerek kısa yolları değerlendirir. ğ) Kullandığı strateji veya stratejileri farklı problemlerin çözümlerine geneller. h) Genellemenin geçerliliğini matematiksel örneklerle değerlendirir.",
    ogrenme_kanitlari: "Açık uçlu sorulardan oluşan çalışma kağıdı, İzleme testi, Performans görevi, Öz değerlendirme ve akran değerlendirme formları",
    sosyal_ve_duygusal_beceriler: "SDB2.2. İş Birliği, SDB3.2. Esneklik",
    degerler: "D3. Çalışkanlık, D7. Estetik, D16. Sorumluluk, D17. Tasarruf",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "ARALIK",
    hafta: "13. HAFTA (14-20 ARALIK)",
    haftaNo: 13,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (1)",
    konu: "Doğal Sayılarla Dört İşlem İçeren Problem Çözme",
    ogrenme_ciktisi: "MAT.5.1.2. Doğal sayılar ve işlemler içeren gerçek yaşam problemlerini çözebilme",
    outcomeCode: "MAT.5.1.2",
    surec_bilesenleri: "a) Problemin içerdiği sayı ve işlem bileşenlerini belirler. b) Problemde verilenler ile istenenlerin gerektirdiği işlemler arasındaki ilişkiyi belirler. c) Problem bağlamıyla ilişkili verilenleri uygun matematiksel temsillere dönüştürür. ç) Problemi matematiksel temsiller kullanarak kendi ifadeleri ile açıklar. d) Problemin sonucuna ilişkin tahminde bulunur ve işlemleri gerçekleştirmek için stratejiler geliştirir. e) Belirlenen strateji veya stratejileri çözüm için uygular. f) Çözüm yollarını kontrol eder ve çözüme ulaştırmayan stratejiyi değiştirir. g) Problemin çözümü için kullandığı veya geliştirdiği stratejileri gözden geçirerek kısa yolları değerlendirir. ğ) Kullandığı strateji veya stratejileri farklı problemlerin çözümlerine geneller. h) Genellemenin geçerliliğini matematiksel örneklerle değerlendirir.",
    ogrenme_kanitlari: "Açık uçlu sorulardan oluşan çalışma kağıdı, İzleme testi, Performans görevi, Öz değerlendirme ve akran değerlendirme formları",
    sosyal_ve_duygusal_beceriler: "SDB2.2. İş Birliği, SDB3.2. Esneklik",
    degerler: "D3. Çalışkanlık, D7. Estetik, D16. Sorumluluk, D17. Tasarruf",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "ARALIK",
    hafta: "14. HAFTA (21-27 ARALIK)",
    haftaNo: 14,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (1) - GEOMETRİK NİCELİKLER",
    konu: "Doğal Sayılarla Dört İşlem İçeren Problem Çözme & Dikdörtgenin Çevre Uzunluğu ve Alanı",
    ogrenme_ciktisi: "MAT.5.1.2. Doğal sayılar ve işlemler içeren gerçek yaşam problemlerini çözebilme / MAT.5.4.1. Kenar uzunlukları doğal sayı olan bir dikdörtgenin çevre uzunluğu verildiğinde kenar uzunluklarını yorumlayabilme",
    outcomeCode: "MAT.5.4.1",
    surec_bilesenleri: "a) Kenar uzunlukları doğal sayı olan bir dikdörtgenin çevre uzunluğu verildiğinde olası kenar uzunluklarını inceler. b) Verilen çevre uzunluğuna sahip ve kenar uzunlukları doğal sayı olan dikdörtgen oluşturur. c) Kenar uzunlukları doğal sayı olan farklı dikdörtgenlerin aynı çevre uzunluğuna sahip olabileceğini açıklar.",
    ogrenme_kanitlari: "Açık uçlu sorulardan oluşan çalışma kağıdı, İzleme testi, Performans görevi, Öz değerlendirme ve akran değerlendirme formları",
    sosyal_ve_duygusal_beceriler: "SDB2.2. İş Birliği, SDB3.2. Esneklik",
    degerler: "D3. Çalışkanlık, D7. Estetik, D16. Sorumluluk, D17. Tasarruf",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "ARALIK-OCAK",
    hafta: "15. HAFTA (28 ARALIK - 03 OCAK)",
    haftaNo: 15,
    saat: "5 SAAT",
    unite: "GEOMETRİK NİCELİKLER",
    konu: "Dikdörtgenin Çevre Uzunluğu ve Alanı",
    ogrenme_ciktisi: "MAT.5.4.1. Kenar uzunlukları doğal sayı olan bir dikdörtgenin çevre uzunluğu verildiğinde kenar uzunluklarını yorumlayabilme / MAT.5.4.2. Birim karelerden yola çıkarak dikdörtgenin alanını değerlendirebilme",
    outcomeCode: "MAT.5.4.2",
    surec_bilesenleri: "a) Dikdörtgenin alanını ölçmede, seçtiği birim kareleri ölçüt olarak belirler. b) Dikdörtgenin alanını seçilen birim karelerle ölçer. c) Birim kare sayısının dikdörtgenin iki ardışık kenar uzunluğu ile ilişkisini inceler. ç) Dikdörtgenin alan bağıntısına (iki ardışık kenarın uzunlukları çarpımı) ilişkin yargıda bulunur.",
    ogrenme_kanitlari: "İzleme testi, Açık uçlu sorular, Yapılandırılmış grid, Çalışma kağıdı, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB3.1. Uyum, SDB3.2. Esneklik, SDB3.3. Sorumlu Karar Verme",
    degerler: "D7. Estetik, D14. Saygı",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: "Yılbaşı Tatili"
  },
  {
    ay: "OCAK",
    hafta: "16. HAFTA (04-10 OCAK)",
    haftaNo: 16,
    saat: "5 SAAT",
    unite: "GEOMETRİK NİCELİKLER",
    konu: "Dikdörtgenin Çevre Uzunluğu ve Alanı",
    ogrenme_ciktisi: "MAT.5.4.3. Kenar uzunlukları doğal sayı olan bir dikdörtgenin alanının ölçüsü verildiğinde çevre uzunluğunu, çevre uzunluğu verildiğinde alanını yorumlayabilme",
    outcomeCode: "MAT.5.4.3",
    surec_bilesenleri: "a) Alanının ölçüsü verilen bir dikdörtgenin çevre uzunluğunu, çevre uzunluğu verilen bir dikdörtgenin alanını inceler. b) Aynı alana sahip farklı dikdörtgenlerin çevre uzunluklarını ve aynı çevre uzunluğuna sahip farklı dikdörtgenlerin alanlarını belirler. c) Aynı çevre uzunluğuna sahip dikdörtgenlerin farklı alanlara ve aynı alana sahip dikdörtgenlerin farklı çevre uzunluklarına sahip olabileceğini ifade eder.",
    ogrenme_kanitlari: "İzleme testi, Açık uçlu sorular, Yapılandırılmış grid, Çalışma kağıdı, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB3.1. Uyum, SDB3.2. Esneklik, SDB3.3. Sorumlu Karar Verme",
    degerler: "D7. Estetik, D14. Saygı",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: "SINAV HAFTASI"
  },
  {
    ay: "OCAK",
    hafta: "17. HAFTA (11-17 OCAK)",
    haftaNo: 17,
    saat: "5 SAAT",
    unite: "GEOMETRİK NİCELİKLER",
    konu: "Dikdörtgenin Çevre Uzunluğu ve Alanı",
    ogrenme_ciktisi: "MAT.5.4.4. Dikdörtgenin çevre uzunluğu ve alanı ile ilgili problemleri çözebilme",
    outcomeCode: "MAT.5.4.4",
    surec_bilesenleri: "a) Dikdörtgenin çevre uzunluğu ve alanı ile ilgili problemlerde ilgili matematiksel bileşenleri (şekil, uzunluk, alan ölçüleri gibi) belirler. b) Matematiksel bileşenler arasındaki ilişkileri belirler. c) Problem bağlamındaki temsilleri farklı temsillere dönüştürür. ç) Matematiksel temsillere dönüştürdüğü problemi kendi ifadeleri ile açıklar. d) Problemin sonucuna ilişkin tahminde bulunur ve işlemleri gerçekleştirmek için stratejiler geliştirir. e) Belirlediği stratejileri çözüm için uygular. f) Çözüm yollarını kontrol eder ve çözüme ulaştırmayan stratejiyi değiştirir. g) Problemin çözümü için kullandığı veya geliştirdiği stratejileri gözden geçirerek alternatif çözüm yollarını değerlendirir. ğ) Kullandığı strateji veya stratejileri farklı problemlerin çözümlerine geneller. h) Genellemenin geçerliliğini matematiksel örneklerle değerlendirir.",
    ogrenme_kanitlari: "İzleme testi, Açık uçlu sorular, Yapılandırılmış grid, Çalışma kağıdı, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB3.1. Uyum, SDB3.2. Esneklik, SDB3.3. Sorumlu Karar Verme",
    degerler: "D7. Estetik, D14. Saygı",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "OCAK",
    hafta: "18. HAFTA (18-24 OCAK)",
    haftaNo: 18,
    saat: "5 SAAT",
    unite: "GEOMETRİK NİCELİKLER",
    konu: "Dikdörtgenin Çevre Uzunluğu ve Alanı",
    ogrenme_ciktisi: "MAT.5.4.4. Dikdörtgenin çevre uzunluğu ve alanı ile ilgili problemleri çözebilme",
    outcomeCode: "MAT.5.4.4",
    surec_bilesenleri: "a) Dikdörtgenin çevre uzunluğu ve alanı ile ilgili problemlerde ilgili matematiksel bileşenleri belirler. b) Matematiksel bileşenler arasındaki ilişkileri belirler. c) Problem bağlamındaki temsilleri farklı temsillere dönüştürür. ç) Matematiksel temsillere dönüştürdüğü problemi kendi ifadeleri ile açıklar. d) Problemin sonucuna ilişkin tahminde bulunur ve stratejiler geliştirir. e) Belirlediği stratejileri uygular. f) Çözüm yollarını kontrol eder. g) Alternatif yolları değerlendirir.",
    ogrenme_kanitlari: "İzleme testi, Açık uçlu sorular, Yapılandırılmış grid, Çalışma kağıdı, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB3.1. Uyum, SDB3.2. Esneklik, SDB3.3. Sorumlu Karar Verme",
    degerler: "D7. Estetik, D14. Saygı",
    okuryazarlik_becerileri: "OB2. Dijital Okuryazarlık, OB4. Görsel Okuryazarlık",
    degerlendirme: "Birinci Dönemin Sona Ermesi"
  },
  {
    ay: "ŞUBAT",
    hafta: "19. HAFTA (08-14 ŞUBAT)",
    haftaNo: 19,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (2)",
    konu: "Kesirlerin Farklı Gösterimleri",
    ogrenme_ciktisi: "MAT.5.1.3. Gerçek yaşam durumlarına karşılık gelen kesirleri farklı biçimlerde temsil edebilme",
    outcomeCode: "MAT.5.1.3",
    surec_bilesenleri: "a) Kesirlerin farklı gösterimlerinin (bileşik, tam sayılı, ondalık, yüzde) gerçek yaşam durumu içerisindeki kullanımını anlar. b) Gerçek yaşam durumlarında karşılaşılan kesirlerin farklı gösterimlerini ilişkilendirmek için farklı modelleri (yüzlük kart, somut modeller, sayı doğrusu gibi) seçer. c) Seçilen modelleri kullanır. ç) Kullanılan modelleri kesirlerin farklı gösterimleri ile yorumlar. d) Benzer durumlarda kullanılabilecek farklı modelleri kullanışlılık açısından karşılaştırır. e) Karşılaştırdığı modellerin kullanışlılığına ilişkin karar verir.",
    ogrenme_kanitlari: "Açık uçlu ve kısa cevaplı sorulardan oluşan izleme testi, Açık uçlu sorulardan oluşan çalışma kâğıdı, Öz ve akran değerlendirme formları, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık, SDB3.3. Sorumlu Karar Verme",
    degerler: "D1. Adalet, D5. Duyarlılık, D14. Saygı, D16. Sorumluluk, D17. Tasarruf, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB3. Finansal Okuryazarlık, OB7. Veri Okuryazarlığı",
    degerlendirme: "İkinci Yarıyıl Başlangıcı"
  },
  {
    ay: "ŞUBAT",
    hafta: "20. HAFTA (15-21 ŞUBAT)",
    haftaNo: 20,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (2)",
    konu: "Kesirlerin Farklı Gösterimleri",
    ogrenme_ciktisi: "MAT.5.1.3. Gerçek yaşam durumlarına karşılık gelen kesirleri farklı biçimlerde temsil edebilme",
    outcomeCode: "MAT.5.1.3",
    surec_bilesenleri: "a) Kesirlerin farklı gösterimlerinin (bileşik, tam sayılı, ondalık, yüzde) gerçek yaşam durumu içerisindeki kullanımını anlar. b) Gerçek yaşam durumlarında karşılaşılan kesirlerin farklı gösterimlerini ilişkilendirmek için farklı modelleri seçer. c) Seçilen modelleri kullanır. ç) Kullanılan modelleri kesirlerin farklı gösterimleri ile yorumlar. d) Modelleri kullanışlılık açısından karşılaştırır. e) Karar verir.",
    ogrenme_kanitlari: "Açık uçlu ve kısa cevaplı sorulardan oluşan izleme testi, Açık uçlu sorulardan oluşan çalışma kâğıdı, Öz ve akran değerlendirme formları, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık, SDB3.3. Sorumlu Karar Verme",
    degerler: "D1. Adalet, D5. Duyarlılık, D14. Saygı, D16. Sorumluluk, D17. Tasarruf, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB3. Finansal Okuryazarlık, OB7. Veri Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "ŞUBAT",
    hafta: "21. HAFTA (22-28 ŞUBAT)",
    haftaNo: 21,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (2)",
    konu: "Kesirlerin Farklı Gösterimleri",
    ogrenme_ciktisi: "MAT.5.1.3. Gerçek yaşam durumlarına karşılık gelen kesirleri farklı biçimlerde temsil edebilme",
    outcomeCode: "MAT.5.1.3",
    surec_bilesenleri: "a) Kesirlerin farklı gösterimlerinin gerçek yaşamdaki kullanımını anlar. b) Farklı modelleri seçer. c) Modelleri kullanır. ç) Modelleri yorumlar. d) Modelleri karşılaştırır. e) Karar verir.",
    ogrenme_kanitlari: "Açık uçlu ve kısa cevaplı sorulardan oluşan izleme testi, Açık uçlu sorulardan oluşan çalışma kâğıdı, Öz ve akran değerlendirme formları, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık, SDB3.3. Sorumlu Karar Verme",
    degerler: "D1. Adalet, D5. Duyarlılık, D14. Saygı, D16. Sorumluluk, D17. Tasarruf, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB3. Finansal Okuryazarlık, OB7. Veri Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "MART",
    hafta: "22. HAFTA (01-07 MART)",
    haftaNo: 22,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (2)",
    konu: "Kesirlerin Farklı Gösterimleri & Kesirlerin Karşılaştırılması",
    ogrenme_ciktisi: "MAT.5.1.3. Gerçek yaşam durumlarına karşılık gelen kesirleri farklı biçimlerde temsil edebilme / MAT.5.1.4. Farklı gösterimlerle ifade edilen kesirlerin karşılaştırılmasına yönelik çıkarım yapabilme",
    outcomeCode: "MAT.5.1.4",
    surec_bilesenleri: "a) Farklı gösterimlerle ifade edilen kesirlerin karşılaştırılmasına yönelik varsayımda bulunur. b) Varsayımındaki ilişkileri inceleyerek kesirlerin karşılaştırılmasına yönelik genellemeleri belirler. c) Elde ettiği genellemelerin varsayımını karşılayıp karşılamadığını sayı doğrusu, şekil gibi temsiller üzerinde gösterir. ç) Varsayımı ile ilgili ulaştığı sonuca yönelik matematiksel önermeleri sözel ya da sembolik temsil ile sunar. d) Sunduğu önermelerin tahmin etme becerisine katkısını gerekçelerle açıklar.",
    ogrenme_kanitlari: "Açık uçlu ve kısa cevaplı sorulardan oluşan izleme testi, Çalışma kâğıdı, Öz ve akran değerlendirme formları, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık, SDB3.3. Sorumlu Karar Verme",
    degerler: "D1. Adalet, D5. Duyarlılık, D14. Saygı, D16. Sorumluluk, D17. Tasarruf, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB3. Finansal Okuryazarlık, OB7. Veri Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "MART",
    hafta: "23. HAFTA (15-21 MART)",
    haftaNo: 23,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (2)",
    konu: "Kesirlerin Karşılaştırılması",
    ogrenme_ciktisi: "MAT.5.1.4. Farklı gösterimlerle ifade edilen kesirlerin karşılaştırılmasına yönelik çıkarım yapabilme",
    outcomeCode: "MAT.5.1.4",
    surec_bilesenleri: "a) Kesirlerin karşılaştırılmasına yönelik varsayımda bulunur. b) Genellemeleri belirler. c) Temsiller üzerinde gösterir. ç) Önermeleri sunar. d) Katkısını gerekçelerle açıklar.",
    ogrenme_kanitlari: "Açık uçlu ve kısa cevaplı sorulardan oluşan izleme testi, Çalışma kâğıdı, Öz ve akran değerlendirme formları, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık, SDB3.3. Sorumlu Karar Verme",
    degerler: "D1. Adalet, D5. Duyarlılık, D14. Saygı, D16. Sorumluluk, D17. Tasarruf, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB3. Finansal Okuryazarlık, OB7. Veri Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "MART",
    hafta: "24. HAFTA (22-28 MART)",
    haftaNo: 24,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (2)",
    konu: "Kesirlerin Karşılaştırılması",
    ogrenme_ciktisi: "MAT.5.1.4. Farklı gösterimlerle ifade edilen kesirlerin karşılaştırılmasına yönelik çıkarım yapabilme",
    outcomeCode: "MAT.5.1.4",
    surec_bilesenleri: "a) Kesirlerin karşılaştırılmasına yönelik varsayımda bulunur. b) Genellemeleri belirler. c) Temsiller üzerinde gösterir. ç) Önermeleri sunar. d) Katkısını gerekçelerle açıklar.",
    ogrenme_kanitlari: "Açık uçlu ve kısa cevaplı sorulardan oluşan izleme testi, Çalışma kâğıdı, Öz ve akran değerlendirme formları, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık, SDB3.3. Sorumlu Karar Verme",
    degerler: "D1. Adalet, D5. Duyarlılık, D14. Saygı, D16. Sorumluluk, D17. Tasarruf, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB3. Finansal Okuryazarlık, OB7. Veri Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "MART-NİSAN",
    hafta: "25. HAFTA (29 MART - 04 NİSAN)",
    haftaNo: 25,
    saat: "5 SAAT",
    unite: "SAYILAR VE NİCELİKLER (2)",
    konu: "Kesirlerin Karşılaştırılması",
    ogrenme_ciktisi: "MAT.5.1.4. Farklı gösterimlerle ifade edilen kesirlerin karşılaştırılmasına yönelik çıkarım yapabilme",
    outcomeCode: "MAT.5.1.4",
    surec_bilesenleri: "a) Varsayımda bulunur. b) Genellemeleri belirler. c) Temsiller üzerinde gösterir. ç) Önermeleri sunar. d) Katkısını gerekçelerle açıklar.",
    ogrenme_kanitlari: "Açık uçlu ve kısa cevaplı sorulardan oluşan izleme testi, Çalışma kâğıdı, Öz ve akran değerlendirme formları, Performans görevi",
    sosyal_ve_duygusal_beceriler: "SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık, SDB3.3. Sorumlu Karar Verme",
    degerler: "D1. Adalet, D5. Duyarlılık, D14. Saygı, D16. Sorumluluk, D17. Tasarruf, D19. Vatanseverlik",
    okuryazarlik_becerileri: "OB3. Finansal Okuryazarlık, OB7. Veri Okuryazarlığı",
    degerlendirme: "SINAV HAFTASI"
  },
  {
    ay: "NİSAN",
    hafta: "26. HAFTA (05-11 NİSAN)",
    haftaNo: 26,
    saat: "5 SAAT",
    unite: "İSTATİSTİKSEL ARAŞTIRMA SÜRECİ",
    konu: "Kategorik Veri Dağılımları",
    ogrenme_ciktisi: "MAT.5.5.1. Kategorik veri ile çalışabilme ve veriye dayalı karar verebilme",
    outcomeCode: "MAT.5.5.1",
    surec_bilesenleri: "a) Kategorik veriye dayanan istatistiksel araştırma gerektiren durumları fark eder. b) Araştırma soruları oluşturur. c) Plan yapar. ç) Anket soruları hazırlar. d) Veri toplar. e) Veri görselleştirme aracını (sıklık tablosu, sütun grafiği, daire grafiği) seçer. f) Veriyi analiz eder. g) Sonuçları elde eder. ğ) Gerekçeler sunar. h) Değerlendirir. ı) Yeniden planlar.",
    ogrenme_kanitlari: "Performans görevi, Öz değerlendirme ve akran değerlendirme formları, Gözlem formu, Çalışma kâğıtları",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık, SDB1.2. Öz Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D5. Duyarlılık, D6. Dürüstlük, D17. Tasarruf, D18. Temizlik",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB4. Görsel Okuryazarlık, OB6. Vatandaşlık Okuryazarlığı, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "NİSAN",
    hafta: "27. HAFTA (12-18 NİSAN)",
    haftaNo: 27,
    saat: "5 SAAT",
    unite: "İSTATİSTİKSEL ARAŞTIRMA SÜRECİ",
    konu: "Kategorik Veri Dağılımları",
    ogrenme_ciktisi: "MAT.5.5.1. Kategorik veri ile çalışabilme ve veriye dayalı karar verebilme",
    outcomeCode: "MAT.5.5.1",
    surec_bilesenleri: "a) Kategorik araştırma gerektiren durumları fark eder. b) Sorular oluşturur. c) Plan yapar. ç) Anket hazırlar. d) Veri toplar. e) Görselleştirme aracını seçer. f) Veriyi analiz eder. g) Sonuçları elde eder. ğ) Gerekçeler sunar. h) Değerlendirir. ı) Yeniden planlar.",
    ogrenme_kanitlari: "Performans görevi, Öz değerlendirme ve akran değerlendirme formları, Gözlem formu, Çalışma kâğıtları",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık, SDB1.2. Öz Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D5. Duyarlılık, D6. Dürüstlük, D17. Tasarruf, D18. Temizlik",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB4. Görsel Okuryazarlık, OB6. Vatandaşlık Okuryazarlığı, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "NİSAN",
    hafta: "28. HAFTA (19-25 NİSAN)",
    haftaNo: 28,
    saat: "5 SAAT",
    unite: "İSTATİSTİKSEL ARAŞTIRMA SÜRECİ",
    konu: "Kategorik Veri Dağılımları",
    ogrenme_ciktisi: "MAT.5.5.1. Kategorik veri ile çalışabilme ve veriye dayalı karar verebilme",
    outcomeCode: "MAT.5.5.1",
    surec_bilesenleri: "a) Durumları fark eder. b) Sorular oluşturur. c) Plan yapar. ç) Anket hazırlar. d) Veri toplar. e) Araç seçer. f) Analiz eder. g) Sonuç elde eder. ğ) Gerekçe sunar. h) Değerlendirir. ı) Yeniden planlar.",
    ogrenme_kanitlari: "Performans görevi, Öz değerlendirme ve akran değerlendirme formları, Gözlem formu, Çalışma kâğıtları",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık, SDB1.2. Öz Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D5. Duyarlılık, D6. Dürüstlük, D17. Tasarruf, D18. Temizlik",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB4. Görsel Okuryazarlık, OB6. Vatandaşlık Okuryazarlığı, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: "23 Nisan Ulusal Egemenlik ve Çocuk Bayramı"
  },
  {
    ay: "NİSAN-MAYIS",
    hafta: "29. HAFTA (26 NİSAN - 02 MAYIS)",
    haftaNo: 29,
    saat: "5 SAAT",
    unite: "İSTATİSTİKSEL ARAŞTIRMA SÜRECİ",
    konu: "Kategorik Veri Dağılımları",
    ogrenme_ciktisi: "MAT.5.5.1. Kategorik veri ile çalışabilme ve veriye dayalı karar verebilme / MAT.5.5.2. Başkaları tarafından oluşturulan kategorik veriye dayalı istatistiksel sonuç veya yorumları tartışabilme",
    outcomeCode: "MAT.5.5.2",
    surec_bilesenleri: "a) Başkaları tarafından oluşturulan kategorik veriye dayalı istatistiksel sonuç veya yorumlara yönelik istatistiksel temellendirme yapar. b) Yanlılıkları tespit eder. c) Sonuç veya yorumları çürütür ya da kabul eder.",
    ogrenme_kanitlari: "Performans görevi, Öz değerlendirme ve akran değerlendirme formları, Gözlem formu, Çalışma kâğıtları",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık, SDB1.2. Öz Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D5. Duyarlılık, D6. Dürüstlük, D17. Tasarruf, D18. Temizlik",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB4. Görsel Okuryazarlık, OB6. Vatandaşlık Okuryazarlığı, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: "1 Mayıs Emek ve Dayanışma Günü"
  },
  {
    ay: "MAYIS",
    hafta: "30. HAFTA (03-09 MAYIS)",
    haftaNo: 30,
    saat: "5 SAAT",
    unite: "İSTATİSTİKSEL ARAŞTIRMA SÜRECİ & İŞLEMLERLE CEBİRSEL DÜŞÜNME",
    konu: "Kategorik Veri Dağılımları & Eşitliğin Korunumu",
    ogrenme_ciktisi: "MAT.5.5.2. Başkaları tarafından oluşturulan kategorik veriye dayalı istatistiksel sonuçları tartışabilme / MAT.5.2.1. Eşitliğin korunumuna ve işlem özelliklerine yönelik çıkarım yapabilme",
    outcomeCode: "MAT.5.2.1",
    surec_bilesenleri: "a) Eşitliğin korunumuna, doğal sayılarla toplama ve çarpma işlemlerinin değişme, birleşme; çarpmanın toplama ve çıkarma işlemleri üzerine dağılma özelliklerine yönelik varsayımlarda bulunur. b) Genellemeleri belirler. c) Sınav/örnekler üzerinden sınar. ç) Matematiksel önermeyi sunar. d) Gerekçe sunar.",
    ogrenme_kanitlari: "Performans görevi, Öz değerlendirme ve akran değerlendirme formları, Gözlem formu, Çalışma kâğıtları",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık, SDB1.2. Öz Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D5. Duyarlılık, D6. Dürüstlük, D17. Tasarruf, D18. Temizlik",
    okuryazarlik_becerileri: "OB1. Bilgi Okuryazarlığı, OB2. Dijital Okuryazarlık, OB3. Finansal Okuryazarlık, OB4. Görsel Okuryazarlık, OB6. Vatandaşlık Okuryazarlığı, OB8. Sürdürülebilirlik Okuryazarlığı",
    degerlendirme: ""
  },
  {
    ay: "MAYIS",
    hafta: "31. HAFTA (10-16 MAYIS)",
    haftaNo: 31,
    saat: "5 SAAT",
    unite: "İŞLEMLERLE CEBİRSEL DÜŞÜNME",
    konu: "Değişme-Birleşme ve Dağılma Özellikleri",
    ogrenme_ciktisi: "MAT.5.2.1. Eşitliğin korunumuna ve işlem özelliklerine yönelik çıkarım yapabilme",
    outcomeCode: "MAT.5.2.1",
    surec_bilesenleri: "a) Eşitliğin korunumuna, toplama ve çarpma işlemlerinin değişme, birleşme, dağılma özelliklerine yönelik varsayımlarda bulunur. b) Genellemeleri belirler. c) Sınama yapar. ç) Önerme sunar. d) Katkısına yönelik gerekçe sunar.",
    ogrenme_kanitlari: "Performans görevi, Öz değerlendirme ve akran değerlendirme formları, Gözlem formu, Çalışma kâğıtları",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık, SDB1.2. Öz Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D5. Duyarlılık, D6. Dürüstlük, D17. Tasarruf, D18. Temizlik",
    okuryazarlik_becerileri: "OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "MAYIS",
    hafta: "32. HAFTA (17-23 MAYIS)",
    haftaNo: 32,
    saat: "5 SAAT",
    unite: "İŞLEMLERLE CEBİRSEL DÜŞÜNME",
    konu: "İşlem Önceliği & Örüntüler",
    ogrenme_ciktisi: "MAT.5.2.2. Karşılaştığı günlük hayat ya da matematiksel durumlarda işlem önceliğini yorumlayabilme / MAT.5.2.3. Sayı ve şekil örüntülerinin kuralına ilişkin muhakeme yapabilme",
    outcomeCode: "MAT.5.2.2",
    surec_bilesenleri: "a) Doğal sayılarla dört işlem içeren problemlerde işlem önceliğini inceler. b) İşlem önceliğini uygular. c) İşlem önceliğini açıklar. / MAT.5.2.3: a) Örüntü kuralı varsayımı, b) Genelleme, c) Sınama, ç) Önerme, d) Gerekçe, e) Kapsayıcı örnekler, f) Değerlendirme.",
    ogrenme_kanitlari: "Performans görevi, Öz değerlendirme ve akran değerlendirme formları, Gözlem formu, Çalışma kâğıtları",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık, SDB1.2. Öz Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D5. Duyarlılık, D6. Dürüstlük, D17. Tasarruf, D18. Temizlik",
    okuryazarlik_becerileri: "OB4. Görsel Okuryazarlık",
    degerlendirme: "19 Mayıs Atatürk’ü Anma Gençlik ve Spor Bayramı"
  },
  {
    ay: "MAYIS",
    hafta: "33. HAFTA (24-30 MAYIS)",
    haftaNo: 33,
    saat: "5 SAAT",
    unite: "İŞLEMLERLE CEBİRSEL DÜŞÜNME",
    konu: "Örüntüler",
    ogrenme_ciktisi: "MAT.5.2.3. Sayı ve şekil örüntülerinin kuralına ilişkin muhakeme yapabilme",
    outcomeCode: "MAT.5.2.3",
    surec_bilesenleri: "a) Örüntülerdeki ilişkilere yönelik varsayımda bulunur. b) Varsayıma yönelik örüntüdeki terimleri inceleyerek örüntünün kuralına ilişkin genellemeleri belirler. c) Genellediği ilişkileri sınar. ç) Önermeyi sözel ve sembolik temsillerle sunar. d) Gerekçeler sunar. e) Kapsayıcı örnekler verir. f) Değerlendirir.",
    ogrenme_kanitlari: "Performans görevi, Öz değerlendirme ve akran değerlendirme formları, Gözlem formu, Çalışma kâğıtları",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık, SDB1.2. Öz Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D5. Duyarlılık, D6. Dürüstlük, D17. Tasarruf, D18. Temizlik",
    okuryazarlik_becerileri: "OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "MAYIS-HAZİRAN",
    hafta: "34. HAFTA (31 MAYIS - 06 HAZİRAN)",
    haftaNo: 34,
    saat: "5 SAAT",
    unite: "İŞLEMLERLE CEBİRSEL DÜŞÜNME & VERİDEN OLASILIĞA",
    konu: "Temel Aritmetik İşlemler ve Algoritma / Öznel Olasılık",
    ogrenme_ciktisi: "MAT.5.2.4. Temel aritmetik işlem içeren durumlardaki algoritmaları yorumlayabilme / MAT.5.6.1. Herhangi bir olayın olasılığının 0 ile 1 arasında olduğunu yorumlayabilme",
    outcomeCode: "MAT.5.2.4",
    surec_bilesenleri: "a) Algoritmik yapıyı inceler. b) Tablo temsiline veya aritmetik işlemlere dönüştürür. c) Matematiksel ilişkileri sözlü olarak ifade eder. / MAT.5.6.1: a) Olayları inceler, b) Tahminlerini sayılara dönüştürür, c) Olasılığın 0 ile 1 arasında olduğunu ifade eder.",
    ogrenme_kanitlari: "Performans görevi, Öz değerlendirme ve akran değerlendirme formları, Gözlem formu, Çalışma kâğıtları",
    sosyal_ve_duygusal_beceriler: "SDB1.1. Öz Farkındalık, SDB1.2. Öz Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB2.3. Sosyal Farkındalık",
    degerler: "D5. Duyarlılık, D6. Dürüstlük, D17. Tasarruf, D18. Temizlik",
    okuryazarlik_becerileri: "OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "HAZİRAN",
    hafta: "35. HAFTA (07-13 HAZİRAN)",
    haftaNo: 35,
    saat: "5 SAAT",
    unite: "VERİDEN OLASILIĞA",
    konu: "Öznel Olasılık",
    ogrenme_ciktisi: "MAT.5.6.1. Herhangi bir olayın olasılığının 0 (imkânsız) ile 1 (kesin) arasında (0 ve 1 dâhil) olduğunu ifade edebilme",
    outcomeCode: "MAT.5.6.1",
    surec_bilesenleri: "a) Olayları ve olası durumları inceler. b) Bir olayın olasılığına dair tahminlerini farklı sayı temsillerine dönüştürür. c) Kendi ifadeleriyle tahminde bulunduğu bir olayın olasılığının 0 ile 1 arasında olduğunu ifade eder.",
    ogrenme_kanitlari: "Öz değerlendirme, Akran değerlendirme ve grup değerlendirme formları, Çalışma kâğıdı, Performans görevi, Gözlem formu, İzleme testleri",
    sosyal_ve_duygusal_beceriler: "SDB1.2. Öz Düzenleme, SDB1.3. Öz Yansıtma, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB3.3. Sorumlu Karar Verme",
    degerler: "D1. Adalet",
    okuryazarlik_becerileri: "OB4. Görsel Okuryazarlık",
    degerlendirme: "SINAV HAFTASI"
  },
  {
    ay: "HAZİRAN",
    hafta: "36. HAFTA (14-20 HAZİRAN)",
    haftaNo: 36,
    saat: "5 SAAT",
    unite: "VERİDEN OLASILIĞA",
    konu: "Öznel Olasılık",
    ogrenme_ciktisi: "MAT.5.6.2. Olayları az ya da çok olasılıklı şeklinde yapılandırabilme",
    outcomeCode: "MAT.5.6.2",
    surec_bilesenleri: "a) Olayların olasılıklarına ilişkin nedensel veya mantıksal ilişkiler ortaya koyar. b) Kendi öz bilgisi ile elde ettiği ilişkilere dayanarak olayların olasılıklarını az veya çok olasılıklı şeklinde ortaya koyar.",
    ogrenme_kanitlari: "Öz değerlendirme, Akran ve grup formları, Çalışma kâğıdı, Performans görevi, Gözlem formu, İzleme testleri",
    sosyal_ve_duygusal_beceriler: "SDB1.2. Öz Düzenleme, SDB1.3. Öz Yansıtma, SDB2.1. İletişim, SDB2.2. İş Birliği, SDB3.3. Sorumlu Karar Verme",
    degerler: "D1. Adalet",
    okuryazarlik_becerileri: "OB4. Görsel Okuryazarlık",
    degerlendirme: ""
  },
  {
    ay: "HAZİRAN",
    hafta: "37. HAFTA (21-27 HAZİRAN)",
    haftaNo: 37,
    saat: "5 SAAT",
    unite: "YIL SONU DEĞERLENDİRME - SOSYAL ETKİNLİK",
    konu: "Yıl Sonu Matematik Şenliği & Genel Değerlendirme",
    ogrenme_ciktisi: "Yıl Sonu Genel Tekrar, Beceri ve Değerler Değerlendirmesi",
    outcomeCode: "MAT.5.GENEL",
    surec_bilesenleri: "Yıl boyunca edinilen tüm kavramsal ve sosyal-duygusal becerilerin gözden geçirilmesi ve yansıtılması.",
    ogrenme_kanitlari: "Yıl sonu proje sergisi, Portfolyo değerlendirmesi, Öğrenme günlüğü analizi",
    sosyal_ve_duygusal_beceriler: "SDB1.1, SDB1.2, SDB1.3, SDB2.1, SDB2.2, SDB2.3, SDB3.1, SDB3.2, SDB3.3",
    degerler: "Tüm Maarif Değerleri",
    okuryazarlik_becerileri: "Tüm Okuryazarlık Becerileri",
    degerlendirme: "Ders Yılının Sona Ermesi"
  }
];

export function getAnnualPlanByOutcomeCode(code: string): AnnualPlanItem | undefined {
  if (!code) return undefined;
  const cleanCode = code.trim();
  const exact = ANNUAL_PLAN_DATA.find((p) => p.outcomeCode === cleanCode || p.ogrenme_ciktisi.includes(cleanCode));
  if (exact) return exact;
  return ANNUAL_PLAN_DATA.find((p) => cleanCode.startsWith(p.outcomeCode) || p.outcomeCode.startsWith(cleanCode));
}

export function getAnnualPlanByWeek(weekNumber: number): AnnualPlanItem | undefined {
  return ANNUAL_PLAN_DATA.find((p) => p.haftaNo === weekNumber);
}
