import { PuzzleGameId } from '@/components/lesson-phases/puzzle-phase';
import { getAllOutcomes, getOutcomeById } from '@/lib/curriculum-data';

export interface LessonGameItem {
  id: string;
  gameType: PuzzleGameId;
  title: string;
  tagline: string;
  description: string;
  category: 'arcade' | 'simulation' | 'puzzle' | 'memory' | 'speed' | 'strategy';
  categoryLabel: string;
  categoryIcon: string;
  grade: 5 | 6 | 7;
  gradeLabel: string;
  outcomeId: string;
  outcomeCode: string;
  outcomeTitle: string;
  badge: string;
  reward: string;
  difficulty: 'Kolay' | 'Orta' | 'İleri' | 'Tüm Seviyeler';
  gradient: string;
  isAvailable: boolean;
}

export const CURATED_LESSON_GAMES: LessonGameItem[] = [
  // =========================================================================
  // 5. SINIF - MAT.5.3.1
  // =========================================================================
  {
    id: 'mat-5-3-1-lasershield',
    gameType: 'lasershield',
    title: 'Lazer Kalkanı: Dikme Savunması',
    tagline: 'Sanal Gönye ile 90° Dikme İndirme',
    description: 'Siber şehre yaklaşan lazer doğrularına sanal gönyeni oturt, 90° dikme indirerek kalkanı etkinleştir ve lazeri yansıt!',
    category: 'arcade',
    categoryLabel: 'Lazer Savunması',
    categoryIcon: '🛡️',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.1',
    outcomeCode: 'MAT.5.3.1',
    outcomeTitle: 'Doğru, Doğru Parçası ve Işın Çizimleri & Semboller',
    badge: '3 Seviye • Gönye & Dikme',
    reward: '+100 XP & Lazer Ustası',
    difficulty: 'Orta',
    gradient: 'from-teal-500 via-cyan-600 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-1-orbitrescue',
    gameType: 'orbitrescue',
    title: 'Yörünge Kurtarma: Pergelin Dansı',
    tagline: 'Sanal Pergel ile 360° Çember Çizimi',
    description: 'Pergelin iğneli ucunu merkez noktaya batır, yarıçapı uydunun mesafesine ayarla ve 360° döndürerek çember yörüngeyi kilitle!',
    category: 'simulation',
    categoryLabel: 'Uzay Simülasyonu',
    categoryIcon: '🛰️',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.1',
    outcomeCode: 'MAT.5.3.1',
    outcomeTitle: 'Doğru, Doğru Parçası ve Işın Çizimleri & Semboller',
    badge: '3 Gezegen • Çember & Pergel',
    reward: '+100 XP & Yörünge Mimarı',
    difficulty: 'Orta',
    gradient: 'from-indigo-600 via-purple-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-1-geometryscissors',
    gameType: 'geometryscissors',
    title: 'Geometri Makası: Doğru, Işın, Doğru Parçası',
    tagline: 'Maglev Ray Döşeme & Sınırlar',
    description: 'Kontrol kulesinin sinyallerine göre doğru parçası, ışın veya doğru raylarını döşeyip Maglev trenini hızla geçir!',
    category: 'strategy',
    categoryLabel: 'Ray Döşeme',
    categoryIcon: '🚄',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.1',
    outcomeCode: 'MAT.5.3.1',
    outcomeTitle: 'Doğru, Doğru Parçası ve Işın Çizimleri & Semboller',
    badge: '3 Parkur • Geometrik Terimler',
    reward: '+100 XP & Maglev Makasçısı',
    difficulty: 'Kolay',
    gradient: 'from-emerald-600 via-teal-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-1-lighthouseangle',
    gameType: 'lighthouseangle',
    title: 'Fener Bekçisi: Açı Kıskacı',
    tagline: 'Dar, Dik ve Geniş Açı İletkisi',
    description: 'Tarihi deniz fenerinin ışık kollarını dar, dik veya geniş açılara ayarlayarak gemileri sis ve kayalıklardan kurtar!',
    category: 'arcade',
    categoryLabel: 'Açı & İletki',
    categoryIcon: '🗼',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.1',
    outcomeCode: 'MAT.5.3.1',
    outcomeTitle: 'Doğru, Doğru Parçası ve Işın Çizimleri & Semboller',
    badge: '3 Görev • İletki & Açı Türleri',
    reward: '+100 XP & Fener Bekçisi',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-orange-600 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-1-memory',
    gameType: 'memorycards',
    title: 'Temel Geometrik Kavramlar Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Nokta, Doğru, Doğru Parçası ve Işın modellerini tanımları ve sembolleriyle 3D kartları çevirerek eşleştirin.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.1',
    outcomeCode: 'MAT.5.3.1',
    outcomeTitle: 'Doğru, Doğru Parçası ve Işın Çizimleri & Semboller',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-5-3-1-matching',
    gameType: 'matching',
    title: 'Kavram & Sembol Eşleştirme',
    tagline: 'Geometrik Modelleri Tanı',
    description: 'Geometrik kavramları görsel modelleri, tanımları ve sembolik gösterimleriyle eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.1',
    outcomeCode: 'MAT.5.3.1',
    outcomeTitle: 'Doğru, Doğru Parçası ve Işın Çizimleri & Semboller',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-5-3-1-wordsearch',
    gameType: 'wordsearch',
    title: 'Geometrik Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku; nokta, doğru, ışın ve doğru parçası terimlerini dinamik harf ızgarasında yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.1',
    outcomeCode: 'MAT.5.3.1',
    outcomeTitle: 'Doğru, Doğru Parçası ve Işın Çizimleri & Semboller',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-1-truefalse',
    gameType: 'truefalse',
    title: 'Geometri Hızlı Doğru / Yanlış Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Geometrik önermeleri hızlıca değerlendir, pedagojik gerekçeleri öğren ve puanları topla!',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.1',
    outcomeCode: 'MAT.5.3.1',
    outcomeTitle: 'Doğru, Doğru Parçası ve Işın Çizimleri & Semboller',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 5. SINIF - MAT.5.3.2
  // =========================================================================
  {
    id: 'mat-5-3-2-construction',
    gameType: 'constructiongame',
    title: 'Adım Adım İnşa & Çıkarım Terazisi',
    tagline: 'Gönye, Cetvel, Pergel & Terazi',
    description: 'Kayıp tren rayını gönye ve cetvelle döşe, treni geçir! Açı kollarını pergelle dengele ve çıkarım terazisinde aksiyomları test et.',
    category: 'simulation',
    categoryLabel: 'İnşa Simülasyonu',
    categoryIcon: '📐',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.2',
    outcomeCode: 'MAT.5.3.2',
    outcomeTitle: 'Temel Çizim Çıkarımları & İnşa Deneyimleri',
    badge: '3 Görev • İnşa & Terazi',
    reward: '+130 XP & Usta Rozeti',
    difficulty: 'Orta',
    gradient: 'from-amber-600 via-teal-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-2-memory',
    gameType: 'memorycards',
    title: 'Geometrik İnşa Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Dikme, paralel doğru, pergel açıklığı ve gönye kavramlarını tanımlarıyla 3D kartları çevirerek eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.2',
    outcomeCode: 'MAT.5.3.2',
    outcomeTitle: 'Temel Çizim Çıkarımları & İnşa Deneyimleri',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-5-3-2-matching',
    gameType: 'matching',
    title: 'Temel Çizim Çıkarımları Eşleştirme',
    tagline: 'Geometrik Modelleri Tanı',
    description: 'Pergel adımları, dikme ve paralellik modellerini sembol ve tanımlarıyla eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.2',
    outcomeCode: 'MAT.5.3.2',
    outcomeTitle: 'Temel Çizim Çıkarımları & İnşa Deneyimleri',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-5-3-2-wordsearch',
    gameType: 'wordsearch',
    title: 'İnşa & Çıkarım Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku; dikme, paralel, pergel, gönye terimlerini dinamik harf ızgarasında bulup yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.2',
    outcomeCode: 'MAT.5.3.2',
    outcomeTitle: 'Temel Çizim Çıkarımları & İnşa Deneyimleri',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-2-truefalse',
    gameType: 'truefalse',
    title: 'Geometrik İnşa Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Pergel ve gönye ile dikme/paralel çizim önermelerini hızla değerlendir!',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.2',
    outcomeCode: 'MAT.5.3.2',
    outcomeTitle: 'Temel Çizim Çıkarımları & İnşa Deneyimleri',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 5. SINIF - MAT.5.3.3
  // =========================================================================
  {
    id: 'mat-5-3-3-radar',
    gameType: 'radargame',
    title: 'Açı Radarı: Hedef Kilitlendi!',
    tagline: '360° İletki & Lazer Atışı',
    description: 'Derin uzay radarında 360° dönebilen sanal iletkiyle açıları ölç, iletişim uydularına lazer antenini kilitle!',
    category: 'arcade',
    categoryLabel: 'Arcade Uzay Radarı',
    categoryIcon: '🎯',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.3',
    outcomeCode: 'MAT.5.3.3',
    outcomeTitle: 'Açıları Ölçmek İçin Matematiksel Araç ve Teknoloji',
    badge: '3 Seviye • 360° İletki',
    reward: '+100 XP & Radar Rozeti',
    difficulty: 'Orta',
    gradient: 'from-cyan-500 via-blue-600 to-indigo-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-3-memory',
    gameType: 'memorycards',
    title: 'Açı Çeşitleri & İletki Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Dar, dik, geniş, doğru ve tam açı kavramlarını derece aralıkları ve tanımlarıyla 3D kartları çevirerek eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.3',
    outcomeCode: 'MAT.5.3.3',
    outcomeTitle: 'Açıları Ölçmek İçin Matematiksel Araç ve Teknoloji',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-5-3-3-matching',
    gameType: 'matching',
    title: 'Açı Çeşitleri & İletki Eşleştirme',
    tagline: 'Geometrik Modelleri Tanı',
    description: 'Açı çeşitleri, ışın ve köşe kavramlarını görsel modelleri ve sembolik açı formülleriyle eşleştir.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.3',
    outcomeCode: 'MAT.5.3.3',
    outcomeTitle: 'Açıları Ölçmek İçin Matematiksel Araç ve Teknoloji',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-5-3-3-wordsearch',
    gameType: 'wordsearch',
    title: 'Açı Bilim Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku; iletki, açıölçer, derece, dar, dik, geniş açı kavramlarını bulmaca ızgarasında yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.3',
    outcomeCode: 'MAT.5.3.3',
    outcomeTitle: 'Açıları Ölçmek İçin Matematiksel Araç ve Teknoloji',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-3-truefalse',
    gameType: 'truefalse',
    title: 'Açı Ölçümü Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Açı kolları uzadıkça açı büyür mü? 90 dereceden küçük açılar dar açı mıdır? Hızla değerlendir!',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.3',
    outcomeCode: 'MAT.5.3.3',
    outcomeTitle: 'Açıları Ölçmek İçin Matematiksel Araç ve Teknoloji',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 5. SINIF - MAT.5.3.4
  // =========================================================================
  {
    id: 'mat-5-3-4-junction',
    gameType: 'junctiongame',
    title: 'Kavşak Mimarı: Lazer Yolları & Açı Kilidi',
    tagline: 'Dinamik Kesişim, Şifre & Arcade',
    description: 'Lazer kavşağında ters açıları ve komşu bütünleri çöz, neon arabaları geçir! Açı terazisinde tümler ve bütünler enerjisini topla.',
    category: 'arcade',
    categoryLabel: 'Siberpunk Arcade',
    categoryIcon: '⚡',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.4',
    outcomeCode: 'MAT.5.3.4',
    outcomeTitle: 'Kesişen Doğrular ve Açı Çıkarımları',
    badge: '3 Oyun Modu • Siberpunk',
    reward: '+150 XP & Kavşak Mimarı',
    difficulty: 'İleri',
    gradient: 'from-cyan-600 via-indigo-600 to-amber-600',
    isAvailable: true
  },
  {
    id: 'mat-5-3-4-memory',
    gameType: 'memorycards',
    title: 'Doğrular & Açılar Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Ters açı, komşu açı, tümler açı, bütünler açı modellerini tanımlarıyla 3D kartları çevirerek eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.4',
    outcomeCode: 'MAT.5.3.4',
    outcomeTitle: 'Kesişen Doğrular ve Açı Çıkarımları',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-5-3-4-matching',
    gameType: 'matching',
    title: 'Doğrular & Açı Çıkarımları Eşleştirme',
    tagline: 'Geometrik Modelleri Tanı',
    description: 'Ters, komşu, tümler, bütünler açıları ve kesişen doğruların durumlarını sembol ve tanımlarıyla eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.4',
    outcomeCode: 'MAT.5.3.4',
    outcomeTitle: 'Kesişen Doğrular ve Açı Çıkarımları',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-5-3-4-wordsearch',
    gameType: 'wordsearch',
    title: 'Doğrular & Açılar Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku; ters açı, komşu açı, tümler, bütünler ve kesişen doğrular terimlerini bulmaca ızgarasında yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.4',
    outcomeCode: 'MAT.5.3.4',
    outcomeTitle: 'Kesişen Doğrular ve Açı Çıkarımları',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-5-3-4-truefalse',
    gameType: 'truefalse',
    title: 'Kesişen Doğrular Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Ters açıların ölçüleri birbirine eşit midir? Tümler açıların toplamı 90° midir? Hızla cevap ver!',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 5,
    gradeLabel: '5. Sınıf',
    outcomeId: 'MAT.5.3.4',
    outcomeCode: 'MAT.5.3.4',
    outcomeTitle: 'Kesişen Doğrular ve Açı Çıkarımları',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 6. SINIF - MAT.6.1.1
  // =========================================================================
  {
    id: 'mat-6-1-1-kolileme',
    gameType: 'kolilemefactory',
    title: 'Kolileme Fabrikası: Çarpan Eşleme',
    tagline: 'Arcade Çarpan Eşleme',
    description: 'Banttan gelen kolilerin ürün sayılarını bölen doğru çarpan paketlerini seç, kutuları eksiksiz ve firesiz doldur!',
    category: 'arcade',
    categoryLabel: 'Arcade Fabrika',
    categoryIcon: '📦',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.1',
    outcomeCode: 'MAT.6.1.1',
    outcomeTitle: 'Doğal Sayının Çarpanları ve Katları',
    badge: '4 Seviye • Combo & Süre',
    reward: '+120 XP & Usta Kolici',
    difficulty: 'Orta',
    gradient: 'from-amber-500 via-orange-600 to-amber-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-1-frogjump',
    gameType: 'frogjump',
    title: 'Kat Avcısı Kurbağa: Sayı Doğrusu',
    tagline: 'Ritmik Sıçrama Parkuru',
    description: 'Kurbağayı hedef sayının tam katlarına zıplat! Tuzak nilüfer yapraklarından kaç, çarpan sineklerini yakala.',
    category: 'arcade',
    categoryLabel: 'Platform Parkur',
    categoryIcon: '🐸',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.1',
    outcomeCode: 'MAT.6.1.1',
    outcomeTitle: 'Doğal Sayının Çarpanları ve Katları',
    badge: '4 Seviye • 3 Can',
    reward: '+150 XP & Nilüfer Şampiyonu',
    difficulty: 'Orta',
    gradient: 'from-emerald-500 via-teal-600 to-cyan-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-1-rainbowvault',
    gameType: 'rainbowvault',
    title: 'Gökkuşağı Kasası: Eksik Çarpan',
    tagline: 'Gökkuşağı Yayı Şifresi',
    description: 'Gökkuşağı yayındaki simetrik çarpan eşlerini bul, kayıp çarpanı tuşlayarak çelik kasa kilidini aç!',
    category: 'puzzle',
    categoryLabel: 'Kasa Bulmacası',
    categoryIcon: '🔐',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.1',
    outcomeCode: 'MAT.6.1.1',
    outcomeTitle: 'Doğal Sayının Çarpanları ve Katları',
    badge: '4 Kasa • Şifre Çözücü',
    reward: '+140 XP & Çarpan Dedektifi',
    difficulty: 'Orta',
    gradient: 'from-purple-600 via-indigo-600 to-pink-600',
    isAvailable: true
  },
  {
    id: 'mat-6-1-1-memory',
    gameType: 'memorycards',
    title: 'Çarpanlar & Katlar Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Çarpan, kat, bölen, tam kare ve gökkuşağı kavramlarını tanımlarıyla 3D kartları çevirerek eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.1',
    outcomeCode: 'MAT.6.1.1',
    outcomeTitle: 'Doğal Sayının Çarpanları ve Katları',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-1-matching',
    gameType: 'matching',
    title: 'Çarpanlar & Katlar Eşleştirme',
    tagline: 'Matematiksel Modelleri Tanı',
    description: 'Çarpan, kat, alan ve gökkuşağı kavramlarını sembol ve tanımlarıyla eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.1',
    outcomeCode: 'MAT.6.1.1',
    outcomeTitle: 'Doğal Sayının Çarpanları ve Katları',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-1-wordsearch',
    gameType: 'wordsearch',
    title: 'Çarpan & Kat Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku, gizli çarpan, kat, bölen ve gökkuşağı kavramlarını bulmaca ızgarasında yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.1',
    outcomeCode: 'MAT.6.1.1',
    outcomeTitle: 'Doğal Sayının Çarpanları ve Katları',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-6-1-1-truefalse',
    gameType: 'truefalse',
    title: 'Çarpanlar & Katlar D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Her doğal sayı kendisinin çarpanı mıdır? 1 her sayının çarpanı mıdır? Hızla değerlendir!',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.1',
    outcomeCode: 'MAT.6.1.1',
    outcomeTitle: 'Doğal Sayının Çarpanları ve Katları',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 6. SINIF - MAT.6.1.2
  // =========================================================================
  {
    id: 'mat-6-1-2-kolileme',
    gameType: 'kolilemefactory',
    title: 'Bölünebilme Lazer Tasnifi: Kural Eşleme',
    tagline: 'Son Basamak & Rakam Toplamı',
    description: 'Banttan gelen sayıların 2, 3, 4, 5, 6, 9 ve 10 bölünebilme kriterlerini hızla analiz et, doğru lazer kapısına yönlendir!',
    category: 'arcade',
    categoryLabel: 'Arcade Lazer Tasnifi',
    categoryIcon: '📦',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.2',
    outcomeCode: 'MAT.6.1.2',
    outcomeTitle: 'Bölünebilme Kriterleri ve Çıkarımları',
    badge: '4 Seviye • Hızlı Kriter',
    reward: '+130 XP & Bölünebilme Dedektifi',
    difficulty: 'Orta',
    gradient: 'from-sky-500 via-blue-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-2-frogjump',
    gameType: 'frogjump',
    title: 'Kalan Avcısı Kurbağa: Basamak Parkuru',
    tagline: 'Kalan Bulma & Zıplama',
    description: 'Kurbağayı kalansız bölünen nilüferlere zıplat! Kalanlı sayılardan kaç, altın kriter böceklerini topla.',
    category: 'arcade',
    categoryLabel: 'Platform Parkur',
    categoryIcon: '🐸',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.2',
    outcomeCode: 'MAT.6.1.2',
    outcomeTitle: 'Bölünebilme Kriterleri ve Çıkarımları',
    badge: '4 Seviye • 3 Can',
    reward: '+150 XP & Nilüfer Dedektifi',
    difficulty: 'İleri',
    gradient: 'from-cyan-500 via-teal-600 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-2-rainbowvault',
    gameType: 'rainbowvault',
    title: 'Gizli Rakam Kasası: Eksik Basamak',
    tagline: 'Kasa Kilidi & Kriter Çözücü',
    description: 'Sayılardaki gizli A ve B rakamlarını bölünebilme kurallarına göre hesapla, çelik kasa kilidini aç!',
    category: 'puzzle',
    categoryLabel: 'Kasa Bulmacası',
    categoryIcon: '🔐',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.2',
    outcomeCode: 'MAT.6.1.2',
    outcomeTitle: 'Bölünebilme Kriterleri ve Çıkarımları',
    badge: '4 Kasa • Şifre Çözücü',
    reward: '+140 XP & Kasa Ustası',
    difficulty: 'Orta',
    gradient: 'from-purple-600 via-indigo-600 to-pink-600',
    isAvailable: true
  },
  {
    id: 'mat-6-1-2-memory',
    gameType: 'memorycards',
    title: 'Bölünebilme Kuralları Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: '2, 3, 4, 5, 6, 9, 10 bölünebilme kuralları ve basamak kavramlarını tanımlarıyla eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.2',
    outcomeCode: 'MAT.6.1.2',
    outcomeTitle: 'Bölünebilme Kriterleri ve Çıkarımları',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-2-matching',
    gameType: 'matching',
    title: 'Bölünebilme Kriterleri Eşleştirme',
    tagline: 'Matematiksel Modelleri Tanı',
    description: 'Bölünebilme kurallarını, basamak modellerini ve kalan formüllerini eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.2',
    outcomeCode: 'MAT.6.1.2',
    outcomeTitle: 'Bölünebilme Kriterleri ve Çıkarımları',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-2-wordsearch',
    gameType: 'wordsearch',
    title: 'Bölünebilme Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku, gizli bölünebilme, basamak ve kalan kavramlarını bulmaca ızgarasında yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.2',
    outcomeCode: 'MAT.6.1.2',
    outcomeTitle: 'Bölünebilme Kriterleri ve Çıkarımları',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-6-1-2-truefalse',
    gameType: 'truefalse',
    title: 'Bölünebilme Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Son basamağı çift olan tüm sayılar 2 ile tam bölünür mü? Rakamları toplamı 9 olan sayılar 3 ile de bölünür mü?',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.2',
    outcomeCode: 'MAT.6.1.2',
    outcomeTitle: 'Bölünebilme Kriterleri ve Çıkarımları',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 6. SINIF - MAT.6.1.3
  // =========================================================================
  {
    id: 'mat-6-1-3-kolileme',
    gameType: 'kolilemefactory',
    title: 'Asal Çarpan Fabrikası: Ağaç & Algoritma',
    tagline: 'Asal Yapı Taşları',
    description: 'Gelen sayıları asal çarpanlarına ayır, çarpan ağacını ve bölme merdivenini eksiksiz tamamla!',
    category: 'arcade',
    categoryLabel: 'Arcade Asal Ağacı',
    categoryIcon: '🌳',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.3',
    outcomeCode: 'MAT.6.1.3',
    outcomeTitle: 'Asal Sayılar ve Asal Çarpanlar',
    badge: '4 Seviye • Asal Bloklar',
    reward: '+130 XP & Asal Mimarı',
    difficulty: 'Orta',
    gradient: 'from-amber-500 via-orange-600 to-amber-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-3-frogjump',
    gameType: 'frogjump',
    title: 'Eratosthenes Asal Parkuru',
    tagline: 'Asal Nilüferler',
    description: 'Kurbağayı yalnızca asal sayılara zıplat! 1 ve bileşik sayılardan kaçarak kalburu tamamla.',
    category: 'arcade',
    categoryLabel: 'Platform Parkur',
    categoryIcon: '🐸',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.3',
    outcomeCode: 'MAT.6.1.3',
    outcomeTitle: 'Asal Sayılar ve Asal Çarpanlar',
    badge: '4 Seviye • 1-100 Kalbur',
    reward: '+150 XP & Asal Şampiyonu',
    difficulty: 'İleri',
    gradient: 'from-emerald-500 via-teal-600 to-cyan-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-3-rainbowvault',
    gameType: 'rainbowvault',
    title: 'Kripto Asal Kasa: RSA Şifresi',
    tagline: 'Asal Anahtar Çözme',
    description: 'İki asal sayının çarpımıyla kilitlenen şifreli kasaları asal çarpanlarını bularak çöz!',
    category: 'puzzle',
    categoryLabel: 'Kripto Kasa',
    categoryIcon: '🔐',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.3',
    outcomeCode: 'MAT.6.1.3',
    outcomeTitle: 'Asal Sayılar ve Asal Çarpanlar',
    badge: '4 Kasa • Kripto Kod',
    reward: '+140 XP & Kripto Uzmanı',
    difficulty: 'İleri',
    gradient: 'from-purple-600 via-indigo-600 to-pink-600',
    isAvailable: true
  },
  {
    id: 'mat-6-1-3-memory',
    gameType: 'memorycards',
    title: 'Asal Sayılar ve Çarpanlar Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Asal sayı, kalbur, çarpan ağacı ve algoritma kavramlarını tanımlarıyla 3D kartları çevirerek eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.3',
    outcomeCode: 'MAT.6.1.3',
    outcomeTitle: 'Asal Sayılar ve Asal Çarpanlar',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-3-matching',
    gameType: 'matching',
    title: 'Asal Çarpanlar & Ağaç Eşleştirme',
    tagline: 'Matematiksel Modelleri Tanı',
    description: 'Asal sayı kalburu, çarpan ağacı ve üslü gösterimleri tanımlarıyla eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.3',
    outcomeCode: 'MAT.6.1.3',
    outcomeTitle: 'Asal Sayılar ve Asal Çarpanlar',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-3-wordsearch',
    gameType: 'wordsearch',
    title: 'Asal Sayılar Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku, asal sayı, kalbur, çarpan ağacı ve üslü gösterim kavramlarını yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.3',
    outcomeCode: 'MAT.6.1.3',
    outcomeTitle: 'Asal Sayılar ve Asal Çarpanlar',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-6-1-3-truefalse',
    gameType: 'truefalse',
    title: 'Asal Sayılar Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'En küçük asal sayı 2 midir? 2 dışında çift asal sayı var mıdır? 1 asal mıdır?',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.3',
    outcomeCode: 'MAT.6.1.3',
    outcomeTitle: 'Asal Sayılar ve Asal Çarpanlar',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 6. SINIF - MAT.6.1.4
  // =========================================================================
  {
    id: 'mat-6-1-4-kolileme',
    gameType: 'kolilemefactory',
    title: 'Merhamet Paylaşım Fabrikası: Ortak Bölen',
    tagline: 'Eşit Kap & Bidonlama',
    description: 'Zeytinyağı ve nar ekşisini hiç artmayacak şekilde ortak eşit bidonlara dağıt, firesiz lojistiği sağla!',
    category: 'arcade',
    categoryLabel: 'Arcade Lojistik',
    categoryIcon: '🛢️',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.4',
    outcomeCode: 'MAT.6.1.4',
    outcomeTitle: 'Ortak Kat ve Ortak Bölen Problemleri',
    badge: '4 Seviye • Ortak Bölen',
    reward: '+130 XP & Paylaşım Ustası',
    difficulty: 'Orta',
    gradient: 'from-teal-500 via-emerald-600 to-slate-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-4-frogjump',
    gameType: 'frogjump',
    title: 'Ortak Durak Parkuru: Periyodik Katlar',
    tagline: 'Çift Sayı Doğrusu',
    description: 'Farklı periyotlarla sefer yapan otobüslerin ve fenerlerin ortak buluşma anlarını yakala!',
    category: 'arcade',
    categoryLabel: 'Platform Parkur',
    categoryIcon: '🐸',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.4',
    outcomeCode: 'MAT.6.1.4',
    outcomeTitle: 'Ortak Kat ve Ortak Bölen Problemleri',
    badge: '4 Seviye • Ritmik Buluşma',
    reward: '+150 XP & Periyot Kaptanı',
    difficulty: 'İleri',
    gradient: 'from-blue-500 via-cyan-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-4-rainbowvault',
    gameType: 'rainbowvault',
    title: 'Aralarında Asallık Kasası',
    tagline: 'Ortak Böleni 1 Olan Çiftler',
    description: 'Aralarında asal sayı çiftlerini tespit et, 1 ortak bölen mührünü vurarak gizli hazineyi aç!',
    category: 'puzzle',
    categoryLabel: 'Altın Mühür Kasa',
    categoryIcon: '🔐',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.4',
    outcomeCode: 'MAT.6.1.4',
    outcomeTitle: 'Ortak Kat ve Ortak Bölen Problemleri',
    badge: '4 Kasa • Altın Mühür',
    reward: '+140 XP & Asallık Dedektifi',
    difficulty: 'Orta',
    gradient: 'from-amber-600 via-purple-600 to-rose-600',
    isAvailable: true
  },
  {
    id: 'mat-6-1-4-memory',
    gameType: 'memorycards',
    title: 'Ortak Bölen & Kat Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Ortak bölen, ortak kat, periyot ve aralarında asallık kavramlarını tanımlarıyla eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.4',
    outcomeCode: 'MAT.6.1.4',
    outcomeTitle: 'Ortak Kat ve Ortak Bölen Problemleri',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-4-matching',
    gameType: 'matching',
    title: 'Ortak Bölen & Kat Eşleştirme',
    tagline: 'Matematiksel Modelleri Tanı',
    description: 'Ortak bölen kümeleri, ortak kat doğruları ve aralarında asallık kurallarını eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.4',
    outcomeCode: 'MAT.6.1.4',
    outcomeTitle: 'Ortak Kat ve Ortak Bölen Problemleri',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-6-1-4-wordsearch',
    gameType: 'wordsearch',
    title: 'Ortak Kat & Bölen Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku, ortak bölen, ortak kat, periyot ve aralarında asallık terimlerini yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.4',
    outcomeCode: 'MAT.6.1.4',
    outcomeTitle: 'Ortak Kat ve Ortak Bölen Problemleri',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-6-1-4-truefalse',
    gameType: 'truefalse',
    title: 'Ortak Bölen & Kat Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Aralarında asal sayıların 1 dışında ortak böleni var mıdır? İki sayının ortak katları sonsuza gider mi?',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 6,
    gradeLabel: '6. Sınıf',
    outcomeId: 'MAT.6.1.4',
    outcomeCode: 'MAT.6.1.4',
    outcomeTitle: 'Ortak Kat ve Ortak Bölen Problemleri',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 7. SINIF - MAT.7.1.1
  // =========================================================================
  {
    id: 'mat-7-1-1-setsorting',
    gameType: 'setsorting',
    title: 'Küme Ayıklama İstasyonu (N ⊂ Z ⊂ Q)',
    tagline: 'Arcade Hızlı Sınıflandırma',
    description: 'Ekrana gelen pozitif, negatif, kesirli ve tanımsız sayıları hızla analiz et, doğru sepete (N, Z, Q veya Tanımsız) yerleştir!',
    category: 'arcade',
    categoryLabel: 'Arcade Küme Tasnifi',
    categoryIcon: '🗂️',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1',
    outcomeCode: 'MAT.7.1.1',
    outcomeTitle: 'Doğal, Tam ve Rasyonel Sayıları Yorumlayabilme',
    badge: '10 Soru • Hızlı Karar',
    reward: '+150 XP & Küme Dedektifi',
    difficulty: 'Orta',
    gradient: 'from-purple-600 via-indigo-600 to-blue-700',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-rationalparachute',
    gameType: 'rationalparachute',
    title: 'Rasyonel Paraşütçü: Sayı Doğrusu İnişi',
    tagline: 'Hassas Koordinat & İniş',
    description: 'Verilen rasyonel enerji değerini bulmak için doğru ardışık iki tam sayıyı seç, aralığı paydaya göre dilimle ve paraşütçüyü indir!',
    category: 'arcade',
    categoryLabel: 'Hassas İniş Simülasyonu',
    categoryIcon: '🪂',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1',
    outcomeCode: 'MAT.7.1.1',
    outcomeTitle: 'Doğal, Tam ve Rasyonel Sayıları Yorumlayabilme',
    badge: '3 Görev • Hassas İniş',
    reward: '+150 XP & Hassas Paraşütçü',
    difficulty: 'İleri',
    gradient: 'from-indigo-500 via-blue-600 to-sky-700',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-zerobalance',
    gameType: 'zerobalance',
    title: 'Sıfır Denge Merkezi: Mutlak Değer Kilidi',
    tagline: 'Enerji Kristalleri & Uzaklık',
    description: 'Akıllı evdeki enerji kaçaklarını mutlak değer metresiyle ölç, sıfır noktasına eşit mesafedeki zıt kristallerle dengeyi sağla!',
    category: 'arcade',
    categoryLabel: 'Arcade Enerji Kilidi',
    categoryIcon: '⚡',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1',
    outcomeCode: 'MAT.7.1.1',
    outcomeTitle: 'Doğal, Tam ve Rasyonel Sayıları Yorumlayabilme',
    badge: '2 Kademe • Denge Kilidi',
    reward: '+120 XP & Enerji Mimarı',
    difficulty: 'Orta',
    gradient: 'from-emerald-500 via-teal-600 to-cyan-700',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-memory',
    gameType: 'memorycards',
    title: 'Rasyonel Sayılar Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Rasyonel sayı, mutlak değer, Euler şeması, gizli payda ve tanımsızlık kavramlarını tanımlarıyla 3D kartları çevirerek eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1',
    outcomeCode: 'MAT.7.1.1',
    outcomeTitle: 'Doğal, Tam ve Rasyonel Sayıları Yorumlayabilme',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-matching',
    gameType: 'matching',
    title: 'Rasyonel Sayılar & Kümeler Eşleştirme',
    tagline: 'Matematiksel Modelleri Tanı',
    description: 'Rasyonel sayılar, mutlak değer cetveli, Euler kümeleri ve tanımsızlık modellerini sembol ve tanımlarıyla eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1',
    outcomeCode: 'MAT.7.1.1',
    outcomeTitle: 'Doğal, Tam ve Rasyonel Sayıları Yorumlayabilme',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-wordsearch',
    gameType: 'wordsearch',
    title: 'Rasyonel Sayılar Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku, gizli rasyonel sayı, mutlak değer, Euler ve gizli payda terimlerini bulmaca ızgarasında yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1',
    outcomeCode: 'MAT.7.1.1',
    outcomeTitle: 'Doğal, Tam ve Rasyonel Sayıları Yorumlayabilme',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-truefalse',
    gameType: 'truefalse',
    title: 'Rasyonel Sayılar Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Her tam sayı aynı zamanda bir rasyonel sayı mıdır? Paydası 0 olan rasyonel sayı tanımlı mıdır?',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1',
    outcomeCode: 'MAT.7.1.1',
    outcomeTitle: 'Doğal, Tam ve Rasyonel Sayıları Yorumlayabilme',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 7. SINIF - MAT.7.1.1-2 (Derinleşme)
  // =========================================================================
  {
    id: 'mat-7-1-1-2-metro',
    gameType: 'rationalmetro',
    title: 'Rasyonel Metro Hattı (Durak Eşleme)',
    tagline: 'Hassas İstasyon & Temsil Eşleme',
    description: 'Kesir, ondalık ve tam sayılı metro vagonlarını sayı doğrusundaki doğru durak koordinatlarına ulaştır!',
    category: 'arcade',
    categoryLabel: 'Metro Eşleme Simülasyonu',
    categoryIcon: '🚇',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1-2',
    outcomeCode: 'MAT.7.1.1 (2. Hafta)',
    outcomeTitle: 'Rasyonel Sayıların Sayı Doğrusunda Derinleşmesi',
    badge: 'Hassas Eşleme • Combo Serisi',
    reward: '+150 XP & Metro Makinist',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-600 to-cyan-700',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-2-absolutebalance',
    gameType: 'absolutebalance',
    title: 'Mutlak Terazi: Enerji Dengeleme',
    tagline: 'Sıfıra Mesafe & Mutlak Değer Lazeri',
    description: 'Lazer metresiyle sıfır noktasına olan mutlak uzaklıkları ölç! Eşit mesafedeki zıt rasyonel yükleri terazi kefelerine yerleştir.',
    category: 'arcade',
    categoryLabel: 'Arcade Lazer Terazisi',
    categoryIcon: '⚖️',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1-2',
    outcomeCode: 'MAT.7.1.1 (2. Hafta)',
    outcomeTitle: 'Rasyonel Sayıların Sayı Doğrusunda Derinleşmesi',
    badge: 'Arcade Denge • 3 Seviye',
    reward: '+150 XP & Denge Ustası',
    difficulty: 'Orta',
    gradient: 'from-amber-500 via-orange-600 to-rose-700',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-2-minesweeper',
    gameType: 'numberlineminesweeper',
    title: 'Sayı Doğrusunda Mayın Temizleme',
    tagline: 'Yoğunluk & Aralık Dedektifi',
    description: 'İki rasyonel sayı arasında gizlenen mayınları dedektör ile tespit et! Yoğunluk kuralını kullanarak güvenli koordinatlara adım at.',
    category: 'strategy',
    categoryLabel: 'Strateji Mayın Tarlası',
    categoryIcon: '💣',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1-2',
    outcomeCode: 'MAT.7.1.1 (2. Hafta)',
    outcomeTitle: 'Rasyonel Sayıların Sayı Doğrusunda Derinleşmesi',
    badge: 'Aralık & Hassasiyet • 3 Bölge',
    reward: '+150 XP & Mayın Dedektifi',
    difficulty: 'İleri',
    gradient: 'from-emerald-600 via-teal-600 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-2-memory',
    gameType: 'memorycards',
    title: 'Sayı Doğrusu & Yoğunluk Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Bileşik kesir, yoğunluk özelliği, sonsuz nokta, dilimleme ve mutlak değer kavramlarını 3D kartları çevirerek eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1-2',
    outcomeCode: 'MAT.7.1.1 (2. Hafta)',
    outcomeTitle: 'Rasyonel Sayıların Sayı Doğrusunda Derinleşmesi',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-2-matching',
    gameType: 'matching',
    title: 'Rasyonel Sayılar & Yoğunluk Eşleştirme',
    tagline: 'Matematiksel Modelleri Tanı',
    description: 'Bileşik kesir, aralık dilimleme, yoğunluk özelliği ve mutlak değer mesafe modellerini sembol ve tanımlarıyla eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1-2',
    outcomeCode: 'MAT.7.1.1 (2. Hafta)',
    outcomeTitle: 'Rasyonel Sayıların Sayı Doğrusunda Derinleşmesi',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-2-wordsearch',
    gameType: 'wordsearch',
    title: 'Rasyonel Sayılar & Yoğunluk Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku; bileşik kesir, yoğunluk, sayı doğrusu, mikroskop ve tolerans terimlerini bulmaca ızgarasında yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1-2',
    outcomeCode: 'MAT.7.1.1 (2. Hafta)',
    outcomeTitle: 'Rasyonel Sayıların Sayı Doğrusunda Derinleşmesi',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-1-2-truefalse',
    gameType: 'truefalse',
    title: 'Sayı Doğrusu & Yoğunluk Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Herhangi iki rasyonel sayı arasında sonsuz sayıda rasyonel sayı var mıdır? Mutlak değer daima pozitif midir?',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.1-2',
    outcomeCode: 'MAT.7.1.1 (2. Hafta)',
    outcomeTitle: 'Rasyonel Sayıların Sayı Doğrusunda Derinleşmesi',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 7. SINIF - MAT.7.1.2
  // =========================================================================
  {
    id: 'mat-7-1-2-scale',
    gameType: 'rationalscale',
    title: 'Rasyonel Denge Terazisi',
    tagline: 'Hızlı Karşılaştırma & Semboller',
    description: 'İki rasyonel sayıyı teraziye koy, pay/payda eşitleme veya referans stratejisini kullanarak doğru sembolü (<, =, >) seç ve teraziyi dengele!',
    category: 'arcade',
    categoryLabel: 'Arcade Terazi',
    categoryIcon: '⚖️',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.2',
    outcomeCode: 'MAT.7.1.2',
    outcomeTitle: 'Rasyonel Sayıları Karşılaştırma ve Sıralama',
    badge: 'Arcade Terazi • 6 Soru',
    reward: '+120 XP & Denge Ustası',
    difficulty: 'Orta',
    gradient: 'from-violet-600 via-purple-600 to-indigo-700',
    isAvailable: true
  },
  {
    id: 'mat-7-1-2-negativefreeze',
    gameType: 'negativefreeze',
    title: 'Palandöken Dondurucu Sıralama',
    tagline: 'En Soğuktan En Sıcağa Parkur',
    description: 'Pist sıcaklıklarını ve negatif kesirleri en soğuktan en sıcağa (küçükten büyüğe: <) doğru sıralayarak dağ yolunu aç!',
    category: 'arcade',
    categoryLabel: 'Kutup Sıralama Parkuru',
    categoryIcon: '❄️',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.2',
    outcomeCode: 'MAT.7.1.2',
    outcomeTitle: 'Rasyonel Sayıları Karşılaştırma ve Sıralama',
    badge: 'Sıfıra Yakınlık • 3 Aşama',
    reward: '+150 XP & Zirve Şampiyonu',
    difficulty: 'İleri',
    gradient: 'from-cyan-600 via-teal-600 to-blue-800',
    isAvailable: true
  },
  {
    id: 'mat-7-1-2-turbinespeed',
    gameType: 'turbinespeed',
    title: 'Rüzgar Türbinleri Sürat Yarışı',
    tagline: 'Referans & Ortak Payda Sürati',
    description: 'Türbin kanat hızlarını ortak payda (12, 24) ve yarıma/bütüne yakınlık stratejileriyle en yavaştan en hızlıya sırala ve motorları ateşle!',
    category: 'arcade',
    categoryLabel: 'Hız Kokpiti Yarışı',
    categoryIcon: '💨',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.2',
    outcomeCode: 'MAT.7.1.2',
    outcomeTitle: 'Rasyonel Sayıları Karşılaştırma ve Sıralama',
    badge: 'Hız Kokpiti • 3 Yarış',
    reward: '+140 XP & Rüzgar Mühendisi',
    difficulty: 'İleri',
    gradient: 'from-teal-500 via-emerald-600 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-2-memory',
    gameType: 'memorycards',
    title: 'Karşılaştırma & Sıralama Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Negatif rasyonel sıralama, yarıma yakınlık, bütüne yakınlık ve ortak payda stratejilerini 3D kartları çevirerek eşleştir.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.2',
    outcomeCode: 'MAT.7.1.2',
    outcomeTitle: 'Rasyonel Sayıları Karşılaştırma ve Sıralama',
    badge: '12 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-amber-500 via-rose-600 to-indigo-800',
    isAvailable: true
  },
  {
    id: 'mat-7-1-2-matching',
    gameType: 'matching',
    title: 'Karşılaştırma & Sıralama Eşleştirme',
    tagline: 'Matematiksel Modelleri Tanı',
    description: 'Rasyonel karşılaştırma sembollerini, strateji adımlarını ve referans noktalarını eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.2',
    outcomeCode: 'MAT.7.1.2',
    outcomeTitle: 'Rasyonel Sayıları Karşılaştırma ve Sıralama',
    badge: '4 Çift • Eşleştirme',
    reward: '+50 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-teal-700 to-emerald-800',
    isAvailable: true
  },
  {
    id: 'mat-7-1-2-wordsearch',
    gameType: 'wordsearch',
    title: 'Karşılaştırma & Sıralama Kelime Avı',
    tagline: 'Soru Odaklı Akıl Yürütme',
    description: 'İpuçlarını oku; payda eşitleme, yarıma yakınlık, sıfıra yakınlık, negatif kesir terimlerini yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.2',
    outcomeCode: 'MAT.7.1.2',
    outcomeTitle: 'Rasyonel Sayıları Karşılaştırma ve Sıralama',
    badge: '6 Soru • Dinamik Izgara',
    reward: '+60 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-2-truefalse',
    gameType: 'truefalse',
    title: 'Karşılaştırma & Sıralama Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Negatif iki rasyonel sayıdan mutlak değeri büyük olan daha küçük müdür? Paydaları eşit pozitif kesirlerde payı büyük olan büyük müdür?',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.2',
    outcomeCode: 'MAT.7.1.2',
    outcomeTitle: 'Rasyonel Sayıları Karşılaştırma ve Sıralama',
    badge: '7 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },

  // =========================================================================
  // 7. SINIF - MAT.7.1.3
  // =========================================================================
  {
    id: 'mat-7-1-3-gokbeyfueltank',
    gameType: 'gokbeyfueltank',
    title: 'Gökbey Yakıt Tankı Doldurma-Boşaltma',
    tagline: 'Hedef İtki Seviyesi & Valf Kontrolü',
    description: 'Mevcut yakıt seviyesini hedef rasyonel seviyeye ulaştırmak için doğru kesir miktarını depoya ekle veya tahliye et!',
    category: 'arcade',
    categoryLabel: 'Uzay & İtki Simülasyonu',
    categoryIcon: '🚀',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.3',
    outcomeCode: 'MAT.7.1.3',
    outcomeTitle: 'Rasyonel Sayılarla Toplama ve Çıkarma İşlemleri',
    badge: '4 Görev • Akıllı İtki',
    reward: '+120 XP & Yakıt Komutanı',
    difficulty: 'Orta',
    gradient: 'from-indigo-600 via-teal-600 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-3-memory',
    gameType: 'memorycards',
    title: 'Rasyonel Toplama-Çıkarma 3D Hafıza Kartları',
    tagline: 'Kavramsal Eşleştirme & Bellek',
    description: 'Ortak payda, ters eleman, etkisiz eleman, çıkarma kuralı ve sayı doğrusu modelleme kavramlarını tanımlarıyla 3D kartları çevirerek eşleştirin.',
    category: 'memory',
    categoryLabel: '3D Hafıza Kartı',
    categoryIcon: '🃏',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.3',
    outcomeCode: 'MAT.7.1.3',
    outcomeTitle: 'Rasyonel Sayılarla Toplama ve Çıkarma İşlemleri',
    badge: '10 Kart • 3D Çevirme',
    reward: '+80 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-cyan-600 via-teal-700 to-blue-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-3-matching',
    gameType: 'matching',
    title: 'Toplama-Çıkarma Kavram & Sembol Eşleştirme',
    tagline: 'İşlem Özelliklerini Tanı',
    description: 'Ortak payda, ters eleman, etkisiz eleman ve çıkarma kuralını sembolik gösterimleri ve tanımlarıyla eşleştirin.',
    category: 'puzzle',
    categoryLabel: 'Eşleştirme Bulmacası',
    categoryIcon: '🧩',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.3',
    outcomeCode: 'MAT.7.1.3',
    outcomeTitle: 'Rasyonel Sayılarla Toplama ve Çıkarma İşlemleri',
    badge: '5 Çift • Eşleştirme',
    reward: '+60 XP & Rozet',
    difficulty: 'Kolay',
    gradient: 'from-teal-600 via-emerald-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-3-wordsearch',
    gameType: 'wordsearch',
    title: 'Rasyonel Toplama-Çıkarma Kelime Avı',
    tagline: 'Kavram Dedektifi',
    description: 'İpuçlarını oku; payda, ekok, ters eleman, etkisiz eleman ve çıkarma terimlerini dinamik harf ızgarasında yakala!',
    category: 'puzzle',
    categoryLabel: 'Kelime Bulmacası',
    categoryIcon: '🔍',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.3',
    outcomeCode: 'MAT.7.1.3',
    outcomeTitle: 'Rasyonel Sayılarla Toplama ve Çıkarma İşlemleri',
    badge: '5 Soru • Dinamik Izgara',
    reward: '+70 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-3-truefalse',
    gameType: 'truefalse',
    title: 'Rasyonel İşlemler Hızlı D/Y Testi',
    tagline: 'Hız ve Kavramsal Refleks',
    description: 'Paylar toplanır mı? İki eksi artı yapar mı? Rasyonel işlem önermelerini hızlıca değerlendir, pedagojik açıklamalarla puanları topla!',
    category: 'speed',
    categoryLabel: 'Hız & Refleks',
    categoryIcon: '⚡',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.3',
    outcomeCode: 'MAT.7.1.3',
    outcomeTitle: 'Rasyonel Sayılarla Toplama ve Çıkarma İşlemleri',
    badge: '6 Önerme • Süreli',
    reward: '+100 XP',
    difficulty: 'Tüm Seviyeler',
    gradient: 'from-purple-600 via-pink-700 to-rose-800',
    isAvailable: true
  },
  {
    id: 'mat-7-1-4-quantumareamultiplier',
    gameType: 'quantumareamultiplier' as any,
    title: 'Kuantum Alan Çarpanı (Nano-Grid)',
    tagline: 'Kesişen Alan Modeli & Sadeleştirme',
    description: 'Satır ve sütun dilimlerini seçerek çarpım modelini kur, kesişen kuantum hücreleri aydınlat ve en sade sonuca ulaş!',
    category: 'simulation',
    categoryLabel: 'Alan & Model',
    categoryIcon: '📐',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.4',
    outcomeCode: 'MAT.7.1.4',
    outcomeTitle: 'Rasyonel Sayılarla Çarpma ve Bölme İşlemleri',
    badge: '4 Seviye • Alan Modeli',
    reward: '+100 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-teal-600 via-emerald-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-4-rocketinverterdivision',
    gameType: 'rocketinverterdivision' as any,
    title: 'Ters Takla Roket İtkisi (Bölme)',
    tagline: 'Yörünge Motoru & Ters Çevirip Çarpma',
    description: 'Bölme işlemini ters çevirip çarpma kuralına dönüştür, takla atan kesirle itki gücünü hesaplayıp roketi yörüngeye fırlat!',
    category: 'arcade',
    categoryLabel: 'Uzay & İtki',
    categoryIcon: '🚀',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.4',
    outcomeCode: 'MAT.7.1.4',
    outcomeTitle: 'Rasyonel Sayılarla Çarpma ve Bölme İşlemleri',
    badge: '4 Görev • Yörünge İtkisi',
    reward: '+120 XP & Rozet',
    difficulty: 'Orta',
    gradient: 'from-indigo-600 via-purple-700 to-slate-900',
    isAvailable: true
  },
  {
    id: 'mat-7-1-4-simplificationlaser',
    gameType: 'simplificationlaser' as any,
    title: 'Sadeleştirme Lazeri & Ters Eleman',
    tagline: 'Çapraz Sadeleştirme & Hızlı Çözüm',
    description: 'Çapraz ortak bölenleri lazerle vurup sayıları küçült, çarpmaya göre ters elemanları 1 yaparak sonucu yıldırım hızında bul!',
    category: 'speed',
    categoryLabel: 'Lazer & Refleks',
    categoryIcon: '⚡',
    grade: 7,
    gradeLabel: '7. Sınıf',
    outcomeId: 'MAT.7.1.4',
    outcomeCode: 'MAT.7.1.4',
    outcomeTitle: 'Rasyonel Sayılarla Çarpma ve Bölme İşlemleri',
    badge: '4 Hedef • Çapraz Lazer',
    reward: '+140 XP & Rozet',
    difficulty: 'İleri',
    gradient: 'from-rose-600 via-pink-700 to-slate-900',
    isAvailable: true
  }
];

/**
 * Otomatik Oyun Derleyici:
 * CURATED_LESSON_GAMES içerisindeki özel tasarlanmış oyunları alır.
 * Ayrıca müfredattaki (CURRICULUM_DATA) tüm kazanımları tarar;
 * Eğer henüz manuel oyun eklenmemiş yeni bir kazanım varsa, o kazanımın
 * 4 temel Maarif oyununu (Hafıza Kartları, Eşleştirme, Kelime Avı, Hızlı D/Y)
 * otomatik olarak üretip kataloğa katar.
 * Böylece yeni bir ders tasarlandığında manuel ekleme zorunluluğu ortadan kalkar.
 */
function buildAllLessonGames(): LessonGameItem[] {
  const games: LessonGameItem[] = [...CURATED_LESSON_GAMES];
  const registeredOutcomeIds = new Set(games.map((g) => g.outcomeId));

  try {
    const allOutcomes = getAllOutcomes();
    allOutcomes.forEach((outcome) => {
      // Eğer kazanımın puzzle aşaması tanımlıysa ve henüz oyun listesinde yoksa otomatik üret
      if (outcome.phases?.puzzle && !registeredOutcomeIds.has(outcome.id)) {
        const gradeNum: 5 | 6 | 7 =
          outcome.gradeId === 'grade-7' || outcome.code.startsWith('MAT.7')
            ? 7
            : outcome.gradeId === 'grade-6' || outcome.code.startsWith('MAT.6')
            ? 6
            : 5;
        const gradeLabel = `${gradeNum}. Sınıf`;

        const autoGames: LessonGameItem[] = [
          {
            id: `${outcome.id.toLowerCase().replace(/[^a-z0-9]/g, '-')}-memory`,
            gameType: 'memorycards',
            title: `${outcome.shortTitle} 3D Hafıza Kartları`,
            tagline: 'Kavramsal Eşleştirme & Bellek',
            description: `${outcome.title} kavram ve tanımlarını 3D kartları çevirerek eşleştirin.`,
            category: 'memory',
            categoryLabel: '3D Hafıza Kartı',
            categoryIcon: '🃏',
            grade: gradeNum,
            gradeLabel,
            outcomeId: outcome.id,
            outcomeCode: outcome.code,
            outcomeTitle: outcome.title,
            badge: `${outcome.phases.puzzle.items?.length ? outcome.phases.puzzle.items.length * 2 : 10} Kart • 3D Çevirme`,
            reward: '+80 XP & Rozet',
            difficulty: 'Kolay',
            gradient: 'from-cyan-600 via-teal-700 to-blue-900',
            isAvailable: true
          },
          {
            id: `${outcome.id.toLowerCase().replace(/[^a-z0-9]/g, '-')}-matching`,
            gameType: 'matching',
            title: `${outcome.shortTitle} Kavram & Sembol Eşleştirme`,
            tagline: 'Kavramları Tanı & Eşleştir',
            description: `${outcome.shortTitle} kavramlarını sembolik gösterimleri ve tanımlarıyla eşleştirin.`,
            category: 'puzzle',
            categoryLabel: 'Eşleştirme Bulmacası',
            categoryIcon: '🧩',
            grade: gradeNum,
            gradeLabel,
            outcomeId: outcome.id,
            outcomeCode: outcome.code,
            outcomeTitle: outcome.title,
            badge: `${outcome.phases.puzzle.items?.length || 4} Çift • Eşleştirme`,
            reward: '+50 XP & Rozet',
            difficulty: 'Kolay',
            gradient: 'from-teal-600 via-emerald-700 to-slate-900',
            isAvailable: true
          },
          {
            id: `${outcome.id.toLowerCase().replace(/[^a-z0-9]/g, '-')}-wordsearch`,
            gameType: 'wordsearch',
            title: `${outcome.shortTitle} Kelime Avı`,
            tagline: 'Kavram Avcısı',
            description: `${outcome.shortTitle} ile ilgili temel terimleri dinamik harf ızgarasında yakalayın!`,
            category: 'puzzle',
            categoryLabel: 'Kelime Bulmacası',
            categoryIcon: '🔍',
            grade: gradeNum,
            gradeLabel,
            outcomeId: outcome.id,
            outcomeCode: outcome.code,
            outcomeTitle: outcome.title,
            badge: `${outcome.phases.puzzle.items?.length || 5} Terim • Harf Avı`,
            reward: '+60 XP & Rozet',
            difficulty: 'Orta',
            gradient: 'from-blue-600 via-indigo-700 to-slate-900',
            isAvailable: true
          },
          {
            id: `${outcome.id.toLowerCase().replace(/[^a-z0-9]/g, '-')}-truefalse`,
            gameType: 'truefalse',
            title: `${outcome.shortTitle} Hızlı D/Y Testi`,
            tagline: 'Hız ve Kavramsal Refleks',
            description: `${outcome.shortTitle} konusundaki önermeleri hızlıca değerlendirip puanları toplayın!`,
            category: 'speed',
            categoryLabel: 'Hız & Refleks',
            categoryIcon: '⚡',
            grade: gradeNum,
            gradeLabel,
            outcomeId: outcome.id,
            outcomeCode: outcome.code,
            outcomeTitle: outcome.title,
            badge: '6 Önerme • Süreli',
            reward: '+100 XP',
            difficulty: 'Tüm Seviyeler',
            gradient: 'from-purple-600 via-pink-700 to-rose-800',
            isAvailable: true
          }
        ];

        games.push(...autoGames);
        registeredOutcomeIds.add(outcome.id);
      }
    });
  } catch (err) {
    console.warn('Otomatik ders oyunları üretilirken hata oluştu:', err);
  }

  return games;
}

export const LESSON_GAMES: LessonGameItem[] = buildAllLessonGames();

export interface OutcomeFilterOption {
  id: string;
  code: string;
  shortTitle: string;
  grade: 5 | 6 | 7;
  count: number;
}

/**
 * Filtre Menüsü Seçeneklerini Otomatik Üretir:
 * LESSON_GAMES dizisindeki oyunların kazanımlarını ve oyun sayılarını
 * dinamik olarak gruplayıp listeler.
 */
function buildOutcomeFilterOptions(): OutcomeFilterOption[] {
  const options: OutcomeFilterOption[] = [
    { id: 'all', code: 'TÜMÜ', shortTitle: 'Tüm Kazanımlar', grade: 5, count: LESSON_GAMES.length }
  ];

  const outcomeOrder: string[] = [];
  const countMap: Record<string, number> = {};
  const gameMap: Record<string, LessonGameItem> = {};

  LESSON_GAMES.forEach((game) => {
    if (!countMap[game.outcomeId]) {
      outcomeOrder.push(game.outcomeId);
      countMap[game.outcomeId] = 0;
      gameMap[game.outcomeId] = game;
    }
    countMap[game.outcomeId]++;
  });

  outcomeOrder.forEach((outcomeId) => {
    const firstGame = gameMap[outcomeId];
    const outcome = getOutcomeById(outcomeId);
    options.push({
      id: outcomeId,
      code: firstGame.outcomeCode,
      shortTitle: outcome?.shortTitle || firstGame.outcomeTitle,
      grade: firstGame.grade,
      count: countMap[outcomeId]
    });
  });

  return options;
}

export const OUTCOME_FILTER_OPTIONS: OutcomeFilterOption[] = buildOutcomeFilterOptions();

export function getSystemGameStatistics() {
  const totalLessonGames = LESSON_GAMES.length;
  const standaloneGamesCount = 3; // Matematik Çarkı + Çarpım Tablosu + 3D Hafıza Kartları
  const totalGamesCount = totalLessonGames + standaloneGamesCount;
  const uniqueOutcomesCount = new Set(LESSON_GAMES.map((g) => g.outcomeId)).size;

  const grade5Count = LESSON_GAMES.filter((g) => g.grade === 5).length;
  const grade6Count = LESSON_GAMES.filter((g) => g.grade === 6).length;
  const grade7Count = LESSON_GAMES.filter((g) => g.grade === 7).length;

  return {
    totalGames: totalGamesCount,
    totalLessonGames,
    standaloneGames: standaloneGamesCount,
    totalOutcomes: uniqueOutcomesCount,
    grade5Games: grade5Count,
    grade6Games: grade6Count,
    grade7Games: grade7Count,
    totalPointsAvailable: totalGamesCount * 120,
    totalBadgesCount: uniqueOutcomesCount * 3
  };
}
